import {
  BUSINESS_ADDRESS,
  BUSINESS_ADDRESS_EN,
  BUSINESS_NAME,
  BUSINESS_REG_NUMBER,
  ECOMMERCE_REG_NUMBER,
  LANDLINE_PHONE,
  LEGAL_DOC_VERSION,
  REPRESENTATIVE_NAME,
  REPRESENTATIVE_NAME_EN,
  SUPPORT_EMAIL,
} from "./config";

const I18N = {
  ko: {
    languageOptionKo: "한국어",
    languageOptionEn: "English",
    transcriptionLanguageLabel: "전사 언어",
    transcriptionLanguageHint: "인식 언어는 앱 표시 언어와 별개로 적용됩니다.",
    transcriptionLanguageOptionKo: "한국어",
    transcriptionLanguageOptionEn: "English",
    transcriptionLanguageOptionJa: "日本語",
    legalMenu: "정책 메뉴",
    loadingApp: "앱 초기화 중...",
    authIntro: "AI 음성 기록, 지금 시작하세요.",
    authSubcopy: "로그인 후 바로 파일 업로드와 변환을 시작할 수 있습니다.",
    guestTrialCta: "로그인 없이 체험하기",
    guestUserTitle: "비로그인 체험",
    guestUserSubtitle: "파일 1개당 최대 10분, 총 30분까지 변환할 수 있습니다.",
    guestLoginButton: "로그인하고 월 10시간 사용하기",
    guestTrialHint: "비로그인 체험은 히스토리 저장 없이 현재 화면에서만 결과를 확인합니다.",
    authLanding: {
      badges: {
        free: "무료 월 10시간",
        beta: "오픈 베타",
      },
      hero: "녹음만 올리세요. 바로 쓰는 구조화 녹취 문서가 나옵니다.",
      subcopy: "설교, 통화, 회의에 맞춰 AI가 듣고 교정하고 요약합니다. 결과는 TXT/DOCX와 기록본으로 바로 저장할 수 있습니다.",
      beforeLabel: "Before",
      beforeExample: "\"이번 주 광고 예산이 15% 초과됐고, 다음 주 수정안을 다시 공유해 주세요.\"",
      afterLabel: "After",
      afterTitle: "회의 기록 요약",
      afterBullets: [
        "안건: 예산 초과 15%",
        "결정: 수정안 재공유",
        "후속 조치: 일정/담당 재배정",
      ],
      oursCta: "OURS 소개 보기",
      featureCards: [
        {
          title: "전문 용어 정확도",
          body: "도메인 용어 사전 + 문맥 교정으로 오인식을 줄입니다.",
        },
        {
          title: "구조화된 문서 출력",
          body: "요약, 핵심 포인트, 후속 조치까지 바로 쓰는 형태로 제공합니다.",
        },
        {
          title: "2단계 엔진",
          body: "Whisper 전사 + Gemini 교정으로 속도와 품질을 함께 확보합니다.",
        },
      ],
      testimonialLabel: "베타 사용자 피드백",
      testimonials: [
        "\"회의록 정리 시간이 훨씬 단축됐어요.\"",
        "\"설교 요약본을 바로 저장할 수 있어 편합니다.\"",
        "\"전문 용어가 이전보다 덜 깨집니다.\"",
      ],
    },
    login: "로그인",
    signup: "회원가입",
    namePlaceholder: "이름",
    emailPlaceholder: "이메일",
    passwordPlaceholder: "비밀번호",
    forgotAccount: "아이디/비밀번호 찾기",
    accountRecoveryHint: "가입 이메일을 기억하지 못하면 ours113814@gmail.com으로 문의해 주세요.",
    processing: "처리 중...",
    orSocial: "또는 소셜 로그인",
    connecting: "연결 중...",
    continueGoogle: "Google로 로그인",
    continueKakao: "카카오로 로그인",
    continueApple: "Apple로 로그인",
    defaultUser: "로그인 사용자",
    sessionRemainingLabel: "세션 남은 시간",
    sessionChecking: "확인 중",
    sessionExpired: "만료됨",
    logout: "로그아웃",
    tabs: {
      transcribe: "변환",
      history: "히스토리",
      records: "기록본",
      settings: "설정",
    },
    legal: {
      openPrivacy: "개인정보처리방침",
      openTerms: "이용약관",
      openCompanyPolicy: "회사 정책",
      openNotice: "공지사항",
      openFaq: "자주 묻는 질문",
      docVersion: "문서 버전",
      close: "닫기",
    },
    transcriptionTypes: {
      sermon: "설교",
      phonecall: "통화",
      conversation: "회의",
    },
    contentStyles: {
      sermon: "설교",
      lecture: "강의",
      phonecall: "통화",
      meeting: "회의",
      forum: "포럼",
      debate: "토론",
    },
    recordCategories: {
      meeting_keywords: "회의 중요 키워드",
      clinical_notes: "진료 도움 기록",
      sermon_core_summary: "설교 핵심 요약",
    },
    transcribeSettings: "변환 설정",
    pickFile: "파일 선택",
    noFile: "선택된 파일 없음",
    uploadZoneTitle: "음성 파일을 선택해 업로드하세요",
    uploadZoneHint: "MP3 · M4A · WAV · MP4 · 최대 100MB",
    recordMicTitle: "마이크로 바로 녹음",
    recordMicHint: "기기 마이크 권한을 허용하면 녹음 후 같은 변환 흐름으로 처리됩니다.",
    recordStart: "녹음 시작",
    recordStop: "녹음 중지",
    recordCancel: "취소",
    recordSaving: "저장 중...",
    recordingActive: "녹음 중",
    selectedFileLabel: "선택됨",
    transcribeStart: "변환 시작",
    transcribing: "변환 중...",
    processingTitle: "변환하는 중...",
    processingSubcopy: "잠시만 기다려 주세요",
    processingSteps: {
      uploaded: "음성 파일 업로드 완료",
      recognized: "음성 인식",
      structured: "문서 구조화",
      saved: "결과 저장",
    },
    transcribeResult: "변환 결과",
    taskId: "작업 ID",
    itemType: "유형",
    charCount: "문자 수",
    correctedText: "교정 텍스트",
    transcriptEditTitle: "수정본 편집",
    transcriptEditChanged: "변경됨",
    transcriptEditSaved: "저장됨",
    transcriptEditSave: "수정 저장",
    transcriptEditReset: "되돌리기",
    transcriptEditSaving: "저장 중",
    generateSummary: "설교 요약 생성",
    generateSummaryByType: {
      sermon: "설교 요약 생성",
      lecture: "강의 요약 생성",
      phonecall: "통화 기록 요약 생성",
      meeting: "회의 요약 생성",
      forum: "포럼 요약 생성",
      debate: "토론 요약 생성",
      conversation: "회의 요약 생성",
    },
    generatingSummary: "요약 생성 중...",
    summary: "요약",
    recordGenerateSave: "기록본 생성 및 저장",
    draft: "초안",
    drafting: "생성 중",
    edit: "수정",
    save: "저장",
    recordUpdateSave: "수정 저장",
    saving: "저장 중",
    recordEditorPlaceholder: "{label} 내용을 여기에 편집하세요",
    historyTitle: "최근 변환 기록",
    recordsTitle: "저장 기록본",
    refresh: "새로고침",
    loading: "로딩...",
    noHistory: "변환 기록이 없습니다.",
    noRecords: "저장된 기록본이 없습니다.",
    load: "불러오기",
    delete: "삭제",
    deleting: "삭제 중...",
    deleteAll: "전체 삭제",
    deleteConfirm: "삭제 확인",
    deleteAllConfirm: "전체 삭제 확인",
    cancelAction: "취소",
    active: "진행 중",
    historyScopeHint: "삭제는 현재 로그인한 계정에만 반영되며, 진행 중 작업은 유지됩니다.",
    historyDeleteConfirmHint: "다시 누르면 이 기록이 삭제됩니다.",
    historyDeleteAllConfirmHint: "다시 누르면 진행 중 항목을 제외한 삭제 가능한 기록이 모두 제거됩니다.",
    historyStatusLabels: {
      queued: "대기 중",
      processing: "진행 중",
      completed: "완료",
      error: "오류",
      uploading: "업로드 중",
    },
    selectedTypeHints: {
      sermon: "설교 흐름(본론/결론/기도) 중심으로 구조화합니다.",
      phonecall: "통화 화자 분리와 핵심 문장 중심으로 정리합니다.",
      conversation: "회의 안건/결정/후속 조치를 분리해 정리합니다.",
    },
    settingsTitle: "설정",
    settingsSubtitle: "정책 확인과 앱 환경을 관리합니다.",
    settingsLegalTitle: "법률 문서",
    settingsLegalHint: "개인정보처리방침, 이용약관, 회사 정책을 앱 내 문서 페이지에서 확인하세요.",
    settingsAppearanceTitle: "언어 및 테마",
    settingsAppearanceHint: "언어와 테마를 즉시 변경할 수 있습니다.",
    settingsLanguageLabel: "언어 선택",
    settingsThemeLabel: "테마 선택",
    settingsSupportTitle: "공지 및 도움말",
    settingsSupportHint: "업데이트 공지와 자주 묻는 질문을 앱 내 문서로 확인하세요.",
    settingsUsageTitle: "사용량",
    settingsUsageHint: "이번 달 남은 사용 시간을 확인할 수 있습니다.",
    settingsGlossaryTitle: "사용자 용어집",
    settingsGlossaryHint: "자주 틀리는 고유명사와 전문 용어를 저장해 변환 품질 개선에 사용합니다.",
    glossaryTermPlaceholder: "정확한 표기",
    glossaryMeaningPlaceholder: "뜻/설명",
    glossaryAliasesPlaceholder: "오인식/별칭 (쉼표 또는 줄바꿈)",
    glossaryContextsPlaceholder: "문맥 힌트 (쉼표 또는 줄바꿈)",
    glossaryAdd: "용어 추가",
    glossaryRefresh: "용어 새로고침",
    glossaryEmpty: "아직 저장된 사용자 용어가 없습니다.",
    glossaryDelete: "삭제",
    glossaryDisable: "비활성",
    glossaryEnable: "활성화",
    glossaryActive: "활성",
    glossaryInactive: "비활성",
    glossaryAliasesLabel: "별칭",
    glossaryContextsLabel: "문맥",
    settingsAccountTitle: "계정 관리",
    settingsAccountHint: "계정 삭제 시 로그인 정보, 변환 기록, 저장 기록본 등 앱 데이터가 삭제됩니다.",
    accountDelete: "계정 삭제",
    accountDeleteTitle: "계정을 삭제할까요?",
    accountDeleteMessage: "삭제 후에는 계정과 앱 데이터를 복구할 수 없습니다.",
    accountDeleteCancel: "취소",
    accountDeleteConfirm: "삭제",
    usagePlanLabel: "이용 구분",
    usageThisMonth: "이번 달 사용량",
    usageRemaining: "남은 시간",
    usageUnlimited: "무제한",
    usageWelcomeTrial: "신규 가입 Pro 체험",
    usageWelcomeTrialRemaining: "Pro 체험 {days}일 남음",
    usageLoading: "사용량 정보를 불러오는 중...",
    usageUnavailable: "사용량 정보를 아직 불러오지 못했습니다.",
    usageRefresh: "사용량 새로고침",
    iosFreeOnlyNotice: "iOS에서는 Apple 인앱결제로 Pro 구독을 사용할 수 있습니다.",
    iosUsageNotice: "iOS에서는 Apple 인앱결제로 Pro 구독을 사용할 수 있습니다.",
    appleIapTitle: "Apple Pro 구독",
    appleIapHint: "iOS에서는 App Store 인앱결제로 Pro를 구독하고 무제한 변환을 사용할 수 있습니다.",
    appleIapProductName: "mallog24 Pro 월간 구독",
    appleIapProductPending: "App Store 상품 정보를 불러오는 중...",
    appleIapSubscriptionInfoTitle: "구독 정보",
    appleIapSubscriptionLength: "구독 기간: 1개월 자동 갱신",
    appleIapSubscriptionPriceFallback: "월 ₩8,800",
    appleIapSubscriptionPriceLabel: "구독 가격",
    appleIapSubscriptionPriceNote: "최종 가격은 App Store 계정의 국가 또는 지역에 따라 Apple 결제창에서 확인됩니다.",
    appleIapRequiredInfo: "구독명, 기간, 가격, 개인정보처리방침 및 이용약관을 확인한 뒤 Apple 결제창에서 구독할 수 있습니다.",
    appleIapOpenPrivacy: "개인정보처리방침",
    appleIapOpenTerms: "이용약관(EULA)",
    appleIapStoreUnavailableReady: "App Store 연결을 준비 중입니다. 상품 정보가 늦어도 구독명, 기간, 가격을 확인한 뒤 결제창을 다시 요청할 수 있습니다.",
    appleIapProductUnavailableTitle: "App Store 결제 정보를 확인 중입니다",
    appleIapProductTimeout: "App Store 결제 정보 조회가 지연되고 있습니다. 아래 버튼으로 결제창을 다시 요청해 주세요.",
    appleIapProductIdLabel: "상품 ID",
    appleIapStorefrontLabel: "스토어 지역",
    appleIapProductNotReturned: "App Store가 구독 상품을 아직 반환하지 않았습니다. App Store Connect의 상품 ID, 가격/판매 가능 지역, 앱 버전 연결, 유료 앱 계약 상태를 확인해 주세요.",
    appleIapSimulatorHint: "시뮬레이터에서는 실제 App Store 상품 조회가 제한될 수 있습니다. TestFlight 또는 실제 기기의 Sandbox 계정으로 최종 확인해 주세요.",
    appleIapUnavailable: "App Store 구독 정보를 아직 확인하지 못했습니다. 상품 정보가 늦게 도착하면 아래 버튼으로 App Store 결제창을 다시 요청해 주세요.",
    appleIapConnected: "App Store 연결됨",
    appleIapDisconnected: "App Store 결제 연결을 준비 중입니다. 버튼을 다시 누르면 결제창을 재요청합니다.",
    appleIapSubscribe: "Apple로 Pro 구독하기",
    appleIapRestore: "구매 복원",
    appleIapReload: "상품 다시 불러오기",
    appleIapManage: "Apple 구독 관리",
    appleIapManageFailed: "Apple 구독 관리 화면을 열지 못했습니다.",
    appleIapPurchaseStarted: "Apple 결제창을 여는 중입니다.",
    appleIapPurchaseDispatchTimeout: "Apple 결제창 응답이 지연되고 있습니다. 버튼은 다시 활성화했으니 결제창이 뜨지 않으면 한 번 더 눌러 주세요.",
    appleIapPurchaseVerified: "Apple 구독이 확인되었습니다. Pro 권한을 적용했습니다.",
    appleIapRestoreDone: "Apple 구독 복원이 완료되었습니다.",
    appleIapNoRestorablePurchase: "복원 가능한 Apple 구독을 찾지 못했습니다.",
    appleIapPurchaseFailed: "Apple 결제 처리에 실패했습니다.",
    appleIapVerifyFailed: "Apple 구독 검증에 실패했습니다.",
    appleIapExpired: "Apple 구독이 만료되어 Free 권한으로 표시됩니다.",
    planLabels: {
      guest: "Guest",
      free: "Free",
      pro: "Pro",
      enterprise: "Enterprise",
      admin: "Admin",
    },
    resultSections: {
      body: "본문",
      topic: "주제",
      keyPoint: "핵심",
      summary: "요약",
    },
    resultEmptyValue: "결과 내용을 확인하세요.",
    clipboardCopy: "클립보드 복사",
    exportTxt: "TXT 저장/공유",
    exportDocx: "DOCX 저장/공유",
    exportCopyShort: "복사",
    exportTxtShort: "TXT",
    exportDocxShort: "DOCX",
    privacy: {
      title: "개인정보처리방침 동의",
      version: `정책 버전: ${LEGAL_DOC_VERSION}`,
      body: "mallog24 이용 전 개인정보 및 AI 처리 내용을 확인해주세요. 음성 변환을 요청하면 원본 음성과 변환 텍스트가 제3자 AI 처리 서비스로 전송될 수 있으며, 동의 후 로그인 및 음성 변환 기능을 사용할 수 있습니다.",
      gateNotice: "동의 전에는 로그인과 음성 변환 기능을 사용할 수 없습니다.",
      versionNotice: "정책 버전이 변경되면 다시 동의가 필요합니다.",
      summaryFile: "• 전송 데이터: 사용자가 선택한 원본 음성 파일",
      summaryText: "• 전송 데이터: 음성에서 생성된 변환 텍스트, 요약/교정 요청 내용",
      summaryAi: "• 전송 대상/목적: OpenAI 및 Google(Gemini)에 음성 인식, 텍스트 교정, 요약 생성을 위해 전송",
      summaryStorage: "• 보관: 원본 음성은 처리 후 임시 저장소에서 삭제하고, 변환 텍스트/기록본은 히스토리 제공 범위 내 보관",
      summaryVendors: "• 처리 위탁/보관: Supabase, OpenAI, Google(Gemini)",
      summarySocial: "• 소셜 로그인: Google/Kakao 계정 정보(이메일, 프로필, UID)",
      viewPolicy: "개인정보처리방침 전문 보기",
      viewTerms: "이용약관 보기",
      viewCompanyPolicy: "회사 정책 보기",
      check: "개인정보처리방침을 확인했고 동의합니다.",
      accept: "동의하고 시작하기",
      saving: "저장 중...",
    },
    notices: {
      socialLoginDone: "소셜 로그인이 완료되었습니다.",
      authDoneSignup: "회원가입/로그인이 완료되었습니다.",
      authDoneLogin: "로그인되었습니다.",
      signupDone: "회원가입이 완료되었습니다. 이메일 인증 후 로그인해주세요.",
      loggedOut: "로그아웃되었습니다.",
      fileSelected: "파일이 선택되었습니다.",
      recordingStarted: "녹음을 시작했습니다.",
      recordingReady: "녹음 파일이 준비되었습니다. 변환 시작을 눌러 진행해 주세요.",
      recordingCanceled: "녹음을 취소했습니다.",
      transcribeDone: "변환이 완료되었습니다.",
      requestAccepted: "요청이 접수되었습니다.",
      historyLoaded: "히스토리 결과를 불러왔습니다.",
      historyDeleted: "변환 기록을 삭제했습니다.",
      historyCleared: "삭제 가능한 변환 기록을 모두 삭제했습니다.",
      historyClearedPartial: "삭제 가능한 기록 {deletedCount}건을 삭제했고 진행 중인 {skippedCount}건은 유지했습니다.",
      historyDeleteConfirmPrompt: "삭제를 한 번 더 누르면 이 기록이 제거됩니다.",
      historyDeleteAllConfirmPrompt: "전체 삭제를 한 번 더 누르면 삭제 가능한 기록이 제거됩니다.",
      summaryDone: "요약을 생성했습니다.",
      draftDone: "{label} 초안을 생성했습니다.",
      recordSaved: "기록본을 저장했습니다.",
      recordUpdated: "기록본을 수정했습니다.",
      correctionSaved: "수정 결과를 저장했습니다.",
      correctionNoChange: "저장할 변경 사항이 없습니다.",
      privacyAccepted: "개인정보처리방침 동의가 완료되었습니다.",
      guestUsageLoaded: "비로그인 체험 사용량을 업데이트했습니다.",
      copiedToClipboard: "{label} 내용을 클립보드에 복사했습니다.",
      openedShareTxt: "TXT 저장/공유 창을 열었습니다.",
      openedShareDocx: "DOCX 저장/공유 창을 열었습니다.",
      usageLoaded: "사용량 정보를 업데이트했습니다.",
      accountDeleted: "계정이 삭제되었습니다.",
      passwordResetRequested: "가입된 이메일이라면 비밀번호 재설정 안내 메일이 발송됩니다.",
      glossarySaved: "사용자 용어를 저장했습니다.",
      glossaryUpdated: "사용자 용어를 업데이트했습니다.",
      glossaryDeleted: "사용자 용어를 삭제했습니다.",
    },
    errors: {
      authRequired: "로그인 후 파일 변환을 사용할 수 있습니다.",
      guestTrialLimit: "비로그인 체험은 파일 1개당 최대 10분, 총 30분까지 가능합니다.",
      authInputRequired: "이메일/비밀번호를 입력해주세요.",
      recoveryEmailRequired: "가입에 사용한 이메일을 입력해 주세요.",
      passwordResetFailed: "비밀번호 재설정 메일 요청에 실패했습니다.",
      passwordMin: "비밀번호는 8자 이상이어야 합니다.",
      oauthUrlCreate: "OAuth URL 생성 실패",
      openLoginUrl: "로그인 URL을 열 수 없습니다.",
      socialStartFailed: "소셜 로그인 시작 실패",
      socialSessionFailed: "소셜 로그인 세션 처리 실패",
      socialFailedPrefix: "소셜 로그인 실패",
      fileTooLarge: "파일 크기는 100MB 이하여야 합니다.",
      filePickFailed: "파일 선택 실패",
      fileNotSelected: "먼저 파일을 선택해주세요.",
      recordingPermissionDenied: "마이크 권한이 필요합니다. 기기 설정에서 mallog24의 마이크 접근을 허용해 주세요.",
      recordingStartFailed: "녹음을 시작하지 못했습니다. 마이크 권한과 입력 장치를 확인해 주세요.",
      recordingStopFailed: "녹음을 저장하지 못했습니다. 다시 시도해 주세요.",
      recordingNoFile: "녹음 파일을 찾지 못했습니다. 다시 녹음해 주세요.",
      transcribeFailed: "변환 요청 실패",
      taskNotFound: "작업 상태를 찾을 수 없습니다.",
      transcribeError: "변환 중 오류가 발생했습니다.",
      statusFailed: "상태 조회 실패",
      historyReadFailed: "히스토리 조회 실패",
      historyDeleteFailed: "변환 기록 삭제 실패",
      historyDeleteAllFailed: "전체 기록 삭제 실패",
      recordsReadFailed: "기록본 조회 실패",
      historyLoadFailed: "히스토리 불러오기 실패",
      historyLoadOnlyCompleted: "완료된 작업만 불러올 수 있습니다.",
      summaryFailed: "요약 실패",
      summaryNoText: "요약할 텍스트가 없습니다.",
      draftNeedLogin: "로그인 후 기록본 초안을 생성할 수 있습니다.",
      draftNoSource: "기록본 초안 생성에 필요한 변환 결과가 없습니다.",
      draftFailed: "기록본 초안 생성 실패",
      saveNeedLogin: "로그인 후 기록본 저장이 가능합니다.",
      saveNoContent: "저장할 기록본 내용이 없습니다.",
      saveFailed: "기록본 저장 실패",
      recordUpdateFailed: "기록본 수정 실패",
      correctionNeedLogin: "로그인 후 수정 결과를 저장할 수 있습니다.",
      correctionNoText: "저장할 수정 텍스트가 없습니다.",
      correctionSaveFailed: "수정 결과 저장 실패",
      noExportContent: "내보낼 내용이 없습니다.",
      clipboardFailed: "클립보드 복사에 실패했습니다.",
      shareFailed: "공유 창을 열지 못했습니다.",
      exportModuleMissing: "파일 내보내기 모듈이 없습니다. 앱 의존성을 업데이트해 주세요.",
      shareUnavailable: "이 기기에서는 파일 공유를 지원하지 않습니다.",
      openPrivacyFailed: "개인정보처리방침 페이지를 열 수 없습니다.",
      openPrivacyLinkFailed: "개인정보처리방침 링크를 열 수 없습니다.",
      openTermsFailed: "이용약관 페이지를 열 수 없습니다.",
      openTermsLinkFailed: "이용약관 링크를 열 수 없습니다.",
      openCompanyPolicyFailed: "회사 정책 페이지를 열 수 없습니다.",
      openCompanyPolicyLinkFailed: "회사 정책 링크를 열 수 없습니다.",
      privacySaveFailed: "동의 상태 저장에 실패했습니다. 잠시 후 다시 시도해주세요.",
      usageReadFailed: "사용량 정보를 불러오지 못했습니다.",
      accountDeleteFailed: "계정 삭제에 실패했습니다.",
      glossaryReadFailed: "사용자 용어집을 불러오지 못했습니다.",
      glossarySaveFailed: "사용자 용어 저장에 실패했습니다.",
      glossaryUpdateFailed: "사용자 용어 수정에 실패했습니다.",
      glossaryDeleteFailed: "사용자 용어 삭제에 실패했습니다.",
      glossaryTermRequired: "저장할 용어를 입력해주세요.",
      openExternalFailed: "외부 페이지를 열 수 없습니다.",
      requestFailedPrefix: "요청 실패",
      timeout: "요청 시간이 초과되었습니다. 서버 상태를 확인해주세요.",
      transcribeLongRunning: "처리 시간이 길어지고 있습니다. 잠시 후 히스토리에서 다시 확인해주세요.",
    },
    taskState: {
      waiting: "변환 작업 대기 중...",
      queued: "변환 대기 중...",
      processing: "음성 인식/교정 처리 중...",
      done: "완료",
      uploading: "업로드 중...",
      historyLoading: "히스토리 불러오는 중...",
    },
    authErrors: {
      invalidCredentials: "이메일/비밀번호가 일치하지 않습니다. 기존 계정이 Google/Kakao로 가입된 계정이면 소셜 로그인 버튼을 사용하세요.",
      emailNotConfirmed: "이메일 인증이 완료되지 않았습니다. 인증 메일 확인 후 다시 로그인해주세요.",
      timeout: "인증 서버 응답이 지연되고 있습니다. 잠시 후 다시 시도해주세요.",
      default: "인증 처리 실패",
    },
  },
  en: {
    languageOptionKo: "Korean",
    languageOptionEn: "English",
    transcriptionLanguageLabel: "Transcription language",
    transcriptionLanguageHint: "Recognition language is applied separately from the app display language.",
    transcriptionLanguageOptionKo: "Korean",
    transcriptionLanguageOptionEn: "English",
    transcriptionLanguageOptionJa: "Japanese",
    legalMenu: "Legal menu",
    loadingApp: "Initializing app...",
    authIntro: "Start AI speech records now.",
    authSubcopy: "Sign in to upload files and start transcription.",
    guestTrialCta: "Try without signing in",
    guestUserTitle: "Guest trial",
    guestUserSubtitle: "Up to 10 minutes per file and 30 minutes total.",
    guestLoginButton: "Sign in for 10 free hours/month",
    guestTrialHint: "Guest trial results are shown only on this screen and are not saved to history.",
    authLanding: {
      badges: {
        free: "Free 10h/mo",
        beta: "Open beta",
      },
      hero: "Upload your recording. Get a structured transcript you can use right away.",
      subcopy: "For sermons, calls, and meetings, AI listens, corrects, and summarizes. Save outputs instantly as TXT/DOCX and reusable records.",
      beforeLabel: "Before",
      beforeExample: "\"This week’s ad budget exceeded by 15%. Please share the revised plan again next week.\"",
      afterLabel: "After",
      afterTitle: "Meeting Record Summary",
      afterBullets: [
        "Agenda: Budget overspent by 15%",
        "Decision: Revised plan will be shared",
        "Next action: Reassign timeline/owner",
      ],
      oursCta: "About OURS",
      featureCards: [
        {
          title: "Accurate domain terms",
          body: "Domain dictionaries + context correction reduce misrecognitions.",
        },
        {
          title: "Structured output",
          body: "Get summaries, key points, and follow-up actions in a ready-to-use format.",
        },
        {
          title: "Two-stage engine",
          body: "Whisper transcription + Gemini correction balances speed and quality.",
        },
      ],
      testimonialLabel: "Beta user feedback",
      testimonials: [
        "\"Meeting-note cleanup time dropped significantly.\"",
        "\"It’s convenient to save sermon summaries right away.\"",
        "\"Domain terms break less than before.\"",
      ],
    },
    login: "Log In",
    signup: "Sign Up",
    namePlaceholder: "Name",
    emailPlaceholder: "Email",
    passwordPlaceholder: "Password",
    forgotAccount: "Find account / reset password",
    accountRecoveryHint: "If you cannot remember the sign-up email, contact ours113814@gmail.com.",
    processing: "Processing...",
    orSocial: "or continue with social login",
    connecting: "Connecting...",
    continueGoogle: "Sign in with Google",
    continueKakao: "Log in with Kakao",
    continueApple: "Sign in with Apple",
    defaultUser: "Signed-in user",
    sessionRemainingLabel: "Session expires in",
    sessionChecking: "Checking...",
    sessionExpired: "Expired",
    logout: "Log out",
    tabs: {
      transcribe: "Transcribe",
      history: "History",
      records: "Records",
      settings: "Settings",
    },
    legal: {
      openPrivacy: "Privacy Policy",
      openTerms: "Terms of Service",
      openCompanyPolicy: "Company Policy",
      openNotice: "Notices",
      openFaq: "FAQ",
      docVersion: "Doc version",
      close: "Close",
    },
    transcriptionTypes: {
      sermon: "Sermon",
      phonecall: "Call",
      conversation: "Meeting",
    },
    contentStyles: {
      sermon: "Sermon",
      lecture: "Lecture",
      phonecall: "Call",
      meeting: "Meeting",
      forum: "Forum",
      debate: "Debate",
    },
    recordCategories: {
      meeting_keywords: "Meeting Keywords",
      clinical_notes: "Clinical Notes",
      sermon_core_summary: "Sermon Core Summary",
    },
    transcribeSettings: "Transcription Settings",
    pickFile: "Choose File",
    noFile: "No file selected",
    uploadZoneTitle: "Choose an audio file to upload",
    uploadZoneHint: "MP3 · M4A · WAV · MP4 · up to 100MB",
    recordMicTitle: "Record with microphone",
    recordMicHint: "Allow microphone access to record audio and send it through the same transcription flow.",
    recordStart: "Start recording",
    recordStop: "Stop recording",
    recordCancel: "Cancel",
    recordSaving: "Saving...",
    recordingActive: "Recording",
    selectedFileLabel: "Selected",
    transcribeStart: "Start Transcription",
    transcribing: "Transcribing...",
    processingTitle: "Transcribing...",
    processingSubcopy: "Please wait a moment",
    processingSteps: {
      uploaded: "Audio upload complete",
      recognized: "Speech recognition",
      structured: "Structuring document",
      saved: "Saving result",
    },
    transcribeResult: "Transcription Result",
    taskId: "Task ID",
    itemType: "Type",
    charCount: "Characters",
    correctedText: "Corrected Text",
    transcriptEditTitle: "Edit Transcript",
    transcriptEditChanged: "Changed",
    transcriptEditSaved: "Saved",
    transcriptEditSave: "Save Correction",
    transcriptEditReset: "Reset",
    transcriptEditSaving: "Saving",
    generateSummary: "Generate Summary",
    generateSummaryByType: {
      sermon: "Generate Sermon Summary",
      lecture: "Generate Lecture Summary",
      phonecall: "Generate Call Summary",
      meeting: "Generate Meeting Summary",
      forum: "Generate Forum Summary",
      debate: "Generate Debate Summary",
      conversation: "Generate Meeting Summary",
    },
    generatingSummary: "Generating summary...",
    summary: "Summary",
    recordGenerateSave: "Generate & Save Records",
    draft: "Draft",
    drafting: "Drafting",
    edit: "Edit",
    save: "Save",
    recordUpdateSave: "Save Edit",
    saving: "Saving",
    recordEditorPlaceholder: "Edit {label} content here",
    historyTitle: "Recent History",
    recordsTitle: "Saved Records",
    refresh: "Refresh",
    loading: "Loading...",
    noHistory: "No transcription history.",
    noRecords: "No saved records.",
    load: "Load",
    delete: "Delete",
    deleting: "Deleting...",
    deleteAll: "Delete all",
    deleteConfirm: "Confirm delete",
    deleteAllConfirm: "Confirm delete all",
    cancelAction: "Cancel",
    active: "Active",
    historyScopeHint: "Deletes apply only to the signed-in account, and active tasks stay in place.",
    historyDeleteConfirmHint: "Press delete again to remove this history item.",
    historyDeleteAllConfirmHint: "Press delete all again to remove every deletable item while keeping active tasks.",
    historyStatusLabels: {
      queued: "Queued",
      processing: "Running",
      completed: "Completed",
      error: "Error",
      uploading: "Uploading",
    },
    selectedTypeHints: {
      sermon: "Structures content by sermon flow (message/application/prayer).",
      phonecall: "Focuses on speaker separation and core call statements.",
      conversation: "Separates agenda, decisions, and action items for meetings.",
    },
    settingsTitle: "Settings",
    settingsSubtitle: "Manage legal documents and app preferences.",
    settingsLegalTitle: "Legal Documents",
    settingsLegalHint: "Review privacy policy, terms of service, and company policy in the in-app document page.",
    settingsAppearanceTitle: "Language & Theme",
    settingsAppearanceHint: "Change language and theme instantly.",
    settingsLanguageLabel: "Language",
    settingsThemeLabel: "Theme",
    settingsSupportTitle: "Notices & Help",
    settingsSupportHint: "Read product updates and frequently asked questions in the in-app document page.",
    settingsUsageTitle: "Usage",
    settingsUsageHint: "Check remaining monthly time.",
    settingsGlossaryTitle: "User Glossary",
    settingsGlossaryHint: "Save frequently corrected names and domain terms to improve transcription quality.",
    glossaryTermPlaceholder: "Preferred spelling",
    glossaryMeaningPlaceholder: "Meaning/description",
    glossaryAliasesPlaceholder: "Misrecognitions or aliases (comma or newline)",
    glossaryContextsPlaceholder: "Context hints (comma or newline)",
    glossaryAdd: "Add term",
    glossaryRefresh: "Refresh glossary",
    glossaryEmpty: "No user glossary terms saved yet.",
    glossaryDelete: "Delete",
    glossaryDisable: "Disable",
    glossaryEnable: "Enable",
    glossaryActive: "Active",
    glossaryInactive: "Inactive",
    glossaryAliasesLabel: "Aliases",
    glossaryContextsLabel: "Context",
    settingsAccountTitle: "Account Management",
    settingsAccountHint: "Deleting your account removes your login, transcription history, saved records, and app data.",
    accountDelete: "Delete Account",
    accountDeleteTitle: "Delete your account?",
    accountDeleteMessage: "This permanently removes your account and app data.",
    accountDeleteCancel: "Cancel",
    accountDeleteConfirm: "Delete",
    usagePlanLabel: "Usage type",
    usageThisMonth: "This month usage",
    usageRemaining: "Remaining",
    usageUnlimited: "Unlimited",
    usageWelcomeTrial: "Welcome Pro trial",
    usageWelcomeTrialRemaining: "{days} day(s) left in Pro trial",
    usageLoading: "Loading usage information...",
    usageUnavailable: "Usage information is not available yet.",
    usageRefresh: "Refresh usage",
    iosFreeOnlyNotice: "On iOS, Pro is available through Apple In-App Purchase.",
    iosUsageNotice: "On iOS, Pro is available through Apple In-App Purchase.",
    appleIapTitle: "Apple Pro Subscription",
    appleIapHint: "Subscribe to Pro with App Store In-App Purchase on iOS and use unlimited transcription.",
    appleIapProductName: "mallog24 Pro Monthly Subscription",
    appleIapProductPending: "Loading App Store product...",
    appleIapSubscriptionInfoTitle: "Subscription information",
    appleIapSubscriptionLength: "Subscription period: 1 month, auto-renewing",
    appleIapSubscriptionPriceFallback: "KRW 8,800 / month",
    appleIapSubscriptionPriceLabel: "Subscription price",
    appleIapSubscriptionPriceNote: "The final price is confirmed in the Apple purchase sheet and may vary by App Store country or region.",
    appleIapRequiredInfo: "Review the subscription title, duration, price, Privacy Policy, and Terms of Use before subscribing through Apple.",
    appleIapOpenPrivacy: "Privacy Policy",
    appleIapOpenTerms: "Terms of Use (EULA)",
    appleIapStoreUnavailableReady: "Preparing the App Store connection. You can still review the subscription title, duration, and price, then request the purchase sheet again.",
    appleIapProductUnavailableTitle: "Checking App Store purchase information",
    appleIapProductTimeout: "Loading App Store purchase information is taking longer than expected. Try opening the purchase sheet again below.",
    appleIapProductIdLabel: "Product ID",
    appleIapStorefrontLabel: "Storefront",
    appleIapProductNotReturned: "The App Store has not returned the subscription product yet. Check the product ID, pricing/availability, app-version attachment, and Paid Apps Agreement in App Store Connect.",
    appleIapSimulatorHint: "The iOS Simulator may not load live App Store products. Verify the final flow in TestFlight or on a real device with a Sandbox account.",
    appleIapUnavailable: "App Store subscription information is not ready yet. If it takes longer, try opening the App Store purchase sheet again below.",
    appleIapConnected: "App Store connected",
    appleIapDisconnected: "Preparing the App Store purchase connection. Tap again to request the purchase sheet.",
    appleIapSubscribe: "Subscribe with Apple",
    appleIapRestore: "Restore Purchases",
    appleIapReload: "Reload Product",
    appleIapManage: "Manage Apple Subscription",
    appleIapManageFailed: "Could not open Apple subscription management.",
    appleIapPurchaseStarted: "Opening Apple purchase sheet.",
    appleIapPurchaseDispatchTimeout: "The Apple purchase sheet is taking longer than expected. The button is available again; tap it once more if the sheet does not appear.",
    appleIapPurchaseVerified: "Apple subscription verified. Pro access is active.",
    appleIapRestoreDone: "Apple subscription restored.",
    appleIapNoRestorablePurchase: "No restorable Apple subscription was found.",
    appleIapPurchaseFailed: "Apple purchase failed.",
    appleIapVerifyFailed: "Apple subscription verification failed.",
    appleIapExpired: "Apple subscription is expired, so Free access is shown.",
    planLabels: {
      guest: "Guest",
      free: "Free",
      pro: "Pro",
      enterprise: "Enterprise",
      admin: "Admin",
    },
    resultSections: {
      body: "Body",
      topic: "Topic",
      keyPoint: "Key",
      summary: "Summary",
    },
    resultEmptyValue: "Review the generated result.",
    clipboardCopy: "Copy to Clipboard",
    exportTxt: "Save/Share TXT",
    exportDocx: "Save/Share DOCX",
    exportCopyShort: "Copy",
    exportTxtShort: "TXT",
    exportDocxShort: "DOCX",
    privacy: {
      title: "Privacy Policy Consent",
      version: `Policy version: ${LEGAL_DOC_VERSION}`,
      body: "Please review our privacy and AI processing details before using mallog24. When you request transcription, the source audio and generated text may be sent to third-party AI processors. Login and transcription become available after consent.",
      gateNotice: "Login and transcription stay locked until consent is completed.",
      versionNotice: "If the policy version changes, consent is required again.",
      summaryFile: "• Data sent: source audio files selected by the user",
      summaryText: "• Data sent: generated transcript text and correction/summary request content",
      summaryAi: "• Recipient/purpose: OpenAI and Google (Gemini) for speech recognition, text correction, and summary generation",
      summaryStorage: "• Retention: source audio is deleted from temporary storage after processing; transcript text/records are retained for history features",
      summaryVendors: "• Processors/storage: Supabase, OpenAI, Google (Gemini)",
      summarySocial: "• Social login: Google/Kakao account data (email, profile, UID)",
      viewPolicy: "View full privacy policy",
      viewTerms: "View terms of service",
      viewCompanyPolicy: "View company policy",
      check: "I have reviewed and agree to the Privacy Policy.",
      accept: "Agree and Continue",
      saving: "Saving...",
    },
    notices: {
      socialLoginDone: "Social login completed.",
      authDoneSignup: "Sign-up and login completed.",
      authDoneLogin: "Logged in successfully.",
      signupDone: "Sign-up completed. Please verify your email before login.",
      loggedOut: "You have been logged out.",
      fileSelected: "File selected.",
      recordingStarted: "Recording started.",
      recordingReady: "Recording is ready. Press Start Transcription to continue.",
      recordingCanceled: "Recording canceled.",
      transcribeDone: "Transcription completed.",
      requestAccepted: "Request accepted.",
      historyLoaded: "Loaded selected history result.",
      historyDeleted: "Transcription history item deleted.",
      historyCleared: "All deletable transcription history items were removed.",
      historyClearedPartial: "Deleted {deletedCount} history item(s) and kept {skippedCount} active item(s).",
      historyDeleteConfirmPrompt: "Press Delete once more to remove this history item.",
      historyDeleteAllConfirmPrompt: "Press Delete all once more to remove every deletable history item.",
      summaryDone: "Summary generated.",
      draftDone: "{label} draft generated.",
      recordSaved: "Record saved.",
      recordUpdated: "Record updated.",
      correctionSaved: "Correction saved.",
      correctionNoChange: "No transcript changes to save.",
      privacyAccepted: "Privacy consent saved.",
      guestUsageLoaded: "Guest trial usage updated.",
      copiedToClipboard: "{label} copied to clipboard.",
      openedShareTxt: "TXT save/share sheet opened.",
      openedShareDocx: "DOCX save/share sheet opened.",
      usageLoaded: "Usage information updated.",
      accountDeleted: "Account deleted.",
      passwordResetRequested: "If the email is registered, password reset instructions will be sent.",
      glossarySaved: "User glossary term saved.",
      glossaryUpdated: "User glossary term updated.",
      glossaryDeleted: "User glossary term deleted.",
    },
    errors: {
      authRequired: "Please log in to use transcription.",
      guestTrialLimit: "Guest trial supports up to 10 minutes per file and 30 minutes total.",
      authInputRequired: "Please enter email and password.",
      recoveryEmailRequired: "Please enter the email used for sign-up.",
      passwordResetFailed: "Failed to request password reset email.",
      passwordMin: "Password must be at least 8 characters.",
      oauthUrlCreate: "Failed to create OAuth URL.",
      openLoginUrl: "Unable to open login URL.",
      socialStartFailed: "Failed to start social login",
      socialSessionFailed: "Failed to process social login session",
      socialFailedPrefix: "Social login failed",
      fileTooLarge: "File size must be 100MB or less.",
      filePickFailed: "Failed to select file",
      fileNotSelected: "Please select a file first.",
      recordingPermissionDenied: "Microphone permission is required. Allow microphone access for mallog24 in device settings.",
      recordingStartFailed: "Could not start recording. Please check microphone permission and input device.",
      recordingStopFailed: "Could not save the recording. Please try again.",
      recordingNoFile: "Could not find the recording file. Please record again.",
      transcribeFailed: "Failed to request transcription",
      taskNotFound: "Task status not found.",
      transcribeError: "An error occurred during transcription.",
      statusFailed: "Failed to check task status",
      historyReadFailed: "Failed to fetch history",
      historyDeleteFailed: "Failed to delete history item",
      historyDeleteAllFailed: "Failed to delete all history items",
      recordsReadFailed: "Failed to fetch records",
      historyLoadFailed: "Failed to load history item",
      historyLoadOnlyCompleted: "Only completed tasks can be loaded.",
      summaryFailed: "Failed to generate summary",
      summaryNoText: "No text available to summarize.",
      draftNeedLogin: "Log in to generate record drafts.",
      draftNoSource: "No source text available for draft generation.",
      draftFailed: "Failed to generate record draft",
      saveNeedLogin: "Log in to save records.",
      saveNoContent: "No record content to save.",
      saveFailed: "Failed to save record",
      recordUpdateFailed: "Failed to update record",
      correctionNeedLogin: "Log in to save corrections.",
      correctionNoText: "Edited transcript is empty.",
      correctionSaveFailed: "Failed to save correction",
      noExportContent: "No content to export.",
      clipboardFailed: "Failed to copy to clipboard.",
      shareFailed: "Unable to open share sheet.",
      exportModuleMissing: "File export modules are missing. Please update app dependencies.",
      shareUnavailable: "File sharing is not available on this device.",
      openPrivacyFailed: "Unable to open the privacy policy page.",
      openPrivacyLinkFailed: "Unable to open privacy policy link.",
      openTermsFailed: "Unable to open terms of service page.",
      openTermsLinkFailed: "Unable to open terms of service link.",
      openCompanyPolicyFailed: "Unable to open company policy page.",
      openCompanyPolicyLinkFailed: "Unable to open company policy link.",
      privacySaveFailed: "Failed to save consent state. Please try again.",
      usageReadFailed: "Failed to load usage information.",
      accountDeleteFailed: "Failed to delete account.",
      glossaryReadFailed: "Failed to load user glossary.",
      glossarySaveFailed: "Failed to save user glossary term.",
      glossaryUpdateFailed: "Failed to update user glossary term.",
      glossaryDeleteFailed: "Failed to delete user glossary term.",
      glossaryTermRequired: "Enter a term to save.",
      openExternalFailed: "Unable to open external page.",
      requestFailedPrefix: "Request failed",
      timeout: "Request timed out. Please check server status.",
      transcribeLongRunning: "This task is taking longer than expected. Please check it again from History shortly.",
    },
    taskState: {
      waiting: "Waiting for transcription task...",
      queued: "Queued...",
      processing: "Running speech recognition/correction...",
      done: "Done",
      uploading: "Uploading...",
      historyLoading: "Loading history item...",
    },
    authErrors: {
      invalidCredentials: "Email/password is incorrect. If this account was created with Google/Kakao, use social login.",
      emailNotConfirmed: "Email verification is not complete. Please verify your email first.",
      timeout: "Auth server response is delayed. Please try again shortly.",
      default: "Authentication failed",
    },
  },
};

const SUPPORT_CONTACT_KO = `문의: ${SUPPORT_EMAIL}`;
const SUPPORT_CONTACT_EN = `Contact: ${SUPPORT_EMAIL}`;
const SERVICE_INQUIRY_CONTACT_KO = `서비스 관련 문의: ${SUPPORT_EMAIL}`;
const SERVICE_INQUIRY_CONTACT_EN = `Service inquiries: ${SUPPORT_EMAIL}`;
const BUSINESS_DISCLOSURE_KO = [
  `상호: ${BUSINESS_NAME} | 대표: ${REPRESENTATIVE_NAME} | 사업자등록번호: ${BUSINESS_REG_NUMBER}`,
  `통신판매신고번호: ${ECOMMERCE_REG_NUMBER} | 유선전화번호: ${LANDLINE_PHONE}`,
  `사업장주소: ${BUSINESS_ADDRESS}`,
];
const BUSINESS_DISCLOSURE_EN = [
  `Company name: ${BUSINESS_NAME} | Representative: ${REPRESENTATIVE_NAME_EN} | Business registration no.: ${BUSINESS_REG_NUMBER}`,
  `E-commerce registration no.: ${ECOMMERCE_REG_NUMBER} | Landline: ${LANDLINE_PHONE}`,
  `Business address: ${BUSINESS_ADDRESS_EN}`,
];

const LEGAL_DOCUMENTS = {
  ko: {
    privacy: {
      title: "개인정보처리방침",
      version: LEGAL_DOC_VERSION,
      updatedAt: "최종 업데이트: 2026년 5월 23일",
      sections: [
        {
          title: "1. 처리 항목",
          body: [
            "회원정보(이메일/UID), 소셜로그인(Google/Kakao/Apple ID) 정보, 업로드 음성, 변환 텍스트, 기록본, 접속/오류 로그를 처리할 수 있습니다.",
            "구독 기능 제공을 위해 결제 상태, 상품 ID, 구독 기간, Apple/결제사 거래 식별자를 처리할 수 있으며 카드번호 등 결제수단 원문은 저장하지 않습니다.",
          ],
        },
        {
          title: "2. 처리 목적",
          body: [
            "로그인/계정보호, 전사·교정·요약·기록본 기능 제공, 무료/유료 사용량 관리, iOS App Store 인앱구독 확인, 서비스 보안 및 고객지원 목적입니다.",
          ],
        },
        {
          title: "3. 보관 및 파기",
          body: [
            "원본 음성은 임시 저장 후 처리 완료 시 지체 없이 삭제합니다.",
            "변환 결과/기록본은 기능 제공 범위 내 보관되며 삭제 요청 또는 계정 종료 시 파기됩니다.",
          ],
        },
        {
          title: "4. 위탁 및 국외 처리",
          body: [
            "Supabase(인증/DB), OpenAI(Whisper), Google(Gemini), Apple(Sign in with Apple/App Store 구독)을 이용하며 API 처리 과정에서 국외 서버 처리가 발생할 수 있습니다.",
          ],
        },
        {
          title: "5. 이용자 권리",
          body: [
            "열람·정정·삭제·처리정지를 요청할 수 있으며, 문의 메일로 접수 시 합리적 기간 내 안내합니다.",
            "민감정보 업로드는 지양해 주세요.",
          ],
        },
        {
          title: "6. 문의",
          body: [SUPPORT_CONTACT_KO],
        },
      ],
    },
    terms: {
      title: "이용약관",
      version: LEGAL_DOC_VERSION,
      updatedAt: "시행일: 2026년 5월 23일",
      sections: [
        {
          title: "1. 서비스 범위",
          body: [
            "mallog24는 웹, Android 앱, iOS 앱에서 음성 전사/교정/요약/기록본 저장 기능을 제공합니다.",
            "외부 API 연동 특성상 처리시간과 결과 품질은 환경에 따라 달라질 수 있습니다.",
          ],
        },
        {
          title: "2. 사용량 안내",
          body: [
            "계정·세션 관리 책임은 이용자에게 있으며, 월간 사용량 한도가 적용됩니다.",
            "남은 사용 시간은 설정 화면에서 확인할 수 있습니다.",
            "iOS 앱에서는 Apple App Store 인앱구독으로 Pro를 이용할 수 있으며, 가격·해지·환불은 Apple 결제창과 App Store 정책을 따릅니다.",
          ],
        },
        {
          title: "3. 기능 이용 절차",
          body: [
            "개인정보 및 AI 처리 안내 동의 후 로그인 또는 비로그인 체험으로 변환 기능을 사용할 수 있습니다.",
            "업로드 자료에 대한 적법한 권리를 보유해야 하며 결과는 최종 사용 전 직접 검토해야 합니다.",
          ],
        },
        {
          title: "4. 문의 및 오류 처리",
          body: [
            "서비스 오류 또는 계정 관련 문의는 고객지원 이메일로 접수할 수 있습니다.",
            "접수된 문의는 합리적인 기간 내 순차적으로 확인합니다.",
          ],
        },
        {
          title: "5. 사업자 정보",
          body: [
            ...BUSINESS_DISCLOSURE_KO,
            `고객지원 이메일: ${SUPPORT_EMAIL}`,
          ],
        },
        {
          title: "6. 이용자 책임",
          body: [
            "업로드 자료에 대한 적법한 권리를 보유해야 하며, 타인 권리 침해 자료 업로드를 금지합니다.",
          ],
        },
        {
          title: "7. 금지 행위",
          body: [
            "서비스 우회/공격/비정상 자동화 트래픽, 무단 재판매, 역설계 등 운영을 저해하는 행위를 금지합니다.",
          ],
        },
        {
          title: "8. 제한 및 면책",
          body: [
            "약관 위반 또는 보안위험 시 이용이 제한될 수 있습니다.",
            "전사 결과는 보조 도구이며 최종 검토 책임은 이용자에게 있습니다.",
          ],
        },
        {
          title: "9. 문의",
          body: [SUPPORT_CONTACT_KO],
        },
      ],
    },
    companyPolicy: {
      title: "회사 정책",
      version: LEGAL_DOC_VERSION,
      updatedAt: "최종 업데이트: 2026년 5월 23일",
      sections: [
        {
          title: "1. 운영 원칙",
          body: [
            "정확도·보안·안정성을 우선으로 제품을 개선합니다.",
            "사용자가 빠르게 기록을 재활용할 수 있는 단순한 흐름을 유지합니다.",
            "웹, Android 앱, iOS 앱에서 일관된 핵심 기능과 정책 고지를 유지합니다.",
          ],
        },
        {
          title: "2. 데이터/보안 정책",
          body: [
            "최소 데이터 처리, 권한 분리, HTTPS, 토큰 검증, 요청 제한을 기본 통제로 적용합니다.",
            "Apple ID 로그인과 App Store 구독 정보는 인증·구독 확인 목적에 필요한 범위로만 처리합니다.",
          ],
        },
        {
          title: "3. 품질 정책",
          body: [
            "자동 생성 결과의 사용자 최종 검토를 권장하며, 도메인별 용어 사전/프롬프트를 지속 개선합니다.",
          ],
        },
        {
          title: "4. 책임 있는 AI",
          body: [
            "업로드 데이터는 서비스 목적 내에서만 처리합니다.",
            "불법/권리침해 신고는 내부 기준으로 검토 후 제한 조치할 수 있습니다.",
          ],
        },
        {
          title: "5. 문서 및 기능 변경 관리",
          body: [
            "기능 또는 정책 변경 시 문서 버전·적용일을 포함해 공지합니다.",
            "주요 변경은 앱 내 문서 또는 웹 공지로 안내합니다.",
            "iOS 인앱구독은 Apple 심사, 샌드박스 테스트, 영수증/거래 검증 흐름을 별도 점검합니다.",
          ],
        },
        {
          title: "6. 공지 및 지원",
          body: [
            "주요 정책/장애/기능 변경은 웹/앱 공지로 안내합니다.",
            SUPPORT_CONTACT_KO,
          ],
        },
        {
          title: "7. 사업자 정보",
          body: [
            ...BUSINESS_DISCLOSURE_KO,
            `고객지원 이메일: ${SUPPORT_EMAIL}`,
          ],
        },
      ],
    },
    notice: {
      title: "공지사항",
      version: LEGAL_DOC_VERSION,
      updatedAt: "최종 업데이트: 2026년 5월 23일",
      sections: [
        {
          title: "1. 서비스 안정화 안내",
          body: [
            "대용량 파일 처리 시 응답 지연이 발생할 수 있으며, 처리 상태는 작업 ID 기준으로 계속 확인할 수 있습니다.",
            "백엔드 점검이 필요한 경우 앱 내 배너와 웹 공지를 통해 사전 안내합니다.",
          ],
        },
        {
          title: "2. 정책 문서 개정 안내",
          body: [
            "개인정보처리방침/이용약관/회사정책 개정 시 문서 버전과 시행일을 함께 고지합니다.",
            "중요 변경 사항은 앱 초기 화면 또는 설정 탭에서 확인할 수 있습니다.",
          ],
        },
        {
          title: "3. 문의 채널",
          body: [
            SERVICE_INQUIRY_CONTACT_KO,
          ],
        },
      ],
    },
    faq: {
      title: "자주 묻는 질문 (FAQ)",
      version: LEGAL_DOC_VERSION,
      updatedAt: "최종 업데이트: 2026년 5월 23일",
      sections: [
        {
          title: "Q1. 로그인은 되는데 처리 시작이 느립니다.",
          body: [
            "네트워크 상태, 백엔드 인스턴스 워밍업, 외부 AI API 응답 시간에 따라 초기 지연이 발생할 수 있습니다.",
            "잠시 후 다시 시도하거나 앱을 재실행하면 개선되는 경우가 많습니다.",
          ],
        },
        {
          title: "Q2. 파일 업로드가 실패합니다.",
          body: [
            "파일 용량(최대 100MB), 포맷(mp3/wav/m4a/mp4/webm)과 로그인 상태를 먼저 확인해 주세요.",
            "오류가 반복되면 파일명을 단순화하고 네트워크를 변경해 다시 시도해 주세요.",
          ],
        },
        {
          title: "Q3. 전사 결과가 기대와 다릅니다.",
          body: [
            "배경소음이 적고 화자 구분이 명확한 원본 음성을 권장합니다.",
            "변환 후 요약/기록본 기능으로 문맥을 재정리하면 정확도를 높일 수 있습니다.",
          ],
        },
      ],
    },
  },
  en: {
    privacy: {
      title: "Privacy Policy",
      version: LEGAL_DOC_VERSION,
      updatedAt: "Last updated: May 23, 2026",
      sections: [
        {
          title: "1. Data We Process",
          body: [
            "We may process account data (email/UID), social-login data (Google/Kakao/Apple ID), uploaded audio, transcript text, saved records, and access/error logs.",
            "For subscriptions, we may process payment status, product ID, subscription period, and Apple/payment-provider transaction identifiers. We do not store raw card numbers or full payment credentials.",
          ],
        },
        {
          title: "2. Purpose",
          body: [
            "Used for authentication, account security, transcription/correction/summarization, records, free/paid quota management, iOS App Store in-app subscription verification, support, and service protection.",
          ],
        },
        {
          title: "3. Retention and Deletion",
          body: [
            "Source audio is kept in temporary storage and removed promptly after processing.",
            "Transcripts/records are kept for service features and removed on request or account closure.",
          ],
        },
        {
          title: "4. Processors and Overseas Processing",
          body: [
            "We use Supabase (auth/DB), OpenAI (Whisper), Google (Gemini), and Apple (Sign in with Apple/App Store subscriptions). API processing may involve overseas infrastructure.",
          ],
        },
        {
          title: "5. User Rights",
          body: [
            "You may request access, correction, deletion, and restriction via support email. Avoid uploading unnecessary sensitive data.",
          ],
        },
        {
          title: "6. Contact",
          body: [SUPPORT_CONTACT_EN],
        },
      ],
    },
    terms: {
      title: "Terms of Service",
      version: LEGAL_DOC_VERSION,
      updatedAt: "Effective date: May 23, 2026",
      sections: [
        {
          title: "1. Service Scope",
          body: [
            "mallog24 provides speech transcription, correction, summarization, and structured record features across web, Android, and iOS apps.",
            "Processing time and output quality may vary due to external API dependencies.",
          ],
        },
        {
          title: "2. Usage Quotas",
          body: [
            "Users are responsible for account/session security. Monthly usage quotas apply.",
            "Remaining time can be checked in Settings.",
            "On iOS, Pro may be purchased through Apple App Store in-app subscriptions. Pricing, cancellation, and refunds follow Apple checkout and App Store policies.",
          ],
        },
        {
          title: "3. Feature Use Flow",
          body: [
            "After reviewing the privacy and AI-processing notice, users can use transcription through sign-in or guest mode.",
            "Users must have lawful rights to uploaded content and review generated outputs before final use.",
          ],
        },
        {
          title: "4. Support and Error Handling",
          body: [
            "Service or account questions can be submitted through the support email.",
            "Requests are reviewed in a reasonable order and timeframe.",
          ],
        },
        {
          title: "5. Business Information",
          body: [
            ...BUSINESS_DISCLOSURE_EN,
            `Support email: ${SUPPORT_EMAIL}`,
          ],
        },
        {
          title: "6. User Responsibility",
          body: [
            "Users must have lawful rights to uploaded content and must not infringe third-party rights.",
          ],
        },
        {
          title: "7. Prohibited Conduct",
          body: [
            "Abuse, attacks, bypass attempts, abnormal automation traffic, reverse engineering, and unauthorized resale are prohibited.",
          ],
        },
        {
          title: "8. Restriction and Disclaimer",
          body: [
            "Access may be limited for policy violations or security risks.",
            "Generated outputs are assistive; users are responsible for final review and use.",
          ],
        },
        {
          title: "9. Contact",
          body: [SUPPORT_CONTACT_EN],
        },
      ],
    },
    companyPolicy: {
      title: "Company Policy",
      version: LEGAL_DOC_VERSION,
      updatedAt: "Last updated: May 23, 2026",
      sections: [
        {
          title: "1. Operating Principles",
          body: [
            "We prioritize transcript quality, security, and reliability while keeping workflows simple and practical.",
            "We maintain consistent core features and policy disclosures across web, Android, and iOS apps.",
          ],
        },
        {
          title: "2. Data and Security Standards",
          body: [
            "We apply data minimization, role separation, HTTPS, token validation, and request throttling as baseline controls.",
            "Apple ID sign-in and App Store subscription data are processed only as needed for authentication and subscription verification.",
          ],
        },
        {
          title: "3. Quality Policy",
          body: [
            "Machine-generated outputs should be user-reviewed. Domain-specific prompts and dictionaries are continuously refined.",
          ],
        },
        {
          title: "4. Responsible AI Use",
          body: [
            "Uploaded data is used only for service functionality.",
            "Reported illegal or rights-infringing usage may lead to restrictions under internal policy.",
          ],
        },
        {
          title: "5. Document and Feature Change Governance",
          body: [
            "Policy and feature changes are announced with document version and effective date when needed.",
            "Major changes are shared through web or in-app notices.",
            "iOS in-app subscriptions are managed with a separate checklist for Apple review, sandbox testing, and receipt/transaction verification.",
          ],
        },
        {
          title: "6. Notice and Support",
          body: [
            "Major policy/feature/incident updates are announced via web or in-app notices.",
            SUPPORT_CONTACT_EN,
          ],
        },
        {
          title: "7. Business Information",
          body: [
            ...BUSINESS_DISCLOSURE_EN,
            `Support email: ${SUPPORT_EMAIL}`,
          ],
        },
      ],
    },
    notice: {
      title: "Notices",
      version: LEGAL_DOC_VERSION,
      updatedAt: "Last updated: May 23, 2026",
      sections: [
        {
          title: "1. Service Stability Notice",
          body: [
            "Large files may take longer to process. You can keep tracking status using the task ID.",
            "If backend maintenance is required, we provide advance notice in-app and on the web.",
          ],
        },
        {
          title: "2. Policy Revision Notice",
          body: [
            "When privacy/terms/company policy changes, we announce both document version and effective date.",
            "Major changes are highlighted on the app entry flow or in the Settings tab.",
          ],
        },
        {
          title: "3. Support Channel",
          body: [
            SERVICE_INQUIRY_CONTACT_EN,
          ],
        },
      ],
    },
    faq: {
      title: "Frequently Asked Questions (FAQ)",
      version: LEGAL_DOC_VERSION,
      updatedAt: "Last updated: May 23, 2026",
      sections: [
        {
          title: "Q1. Login works, but processing starts slowly.",
          body: [
            "Initial delays can happen due to network conditions, backend warm-up, or external AI API latency.",
            "Retrying after a short wait or relaunching the app often helps.",
          ],
        },
        {
          title: "Q2. Upload keeps failing.",
          body: [
            "Check file size (max 100MB), supported formats (mp3/wav/m4a/mp4/webm), and sign-in status.",
            "If it keeps failing, simplify the file name and retry on a different network.",
          ],
        },
        {
          title: "Q3. Transcript quality is lower than expected.",
          body: [
            "Use cleaner audio with clear speaker separation when possible.",
            "Post-process with summary/record features to improve final readability and structure.",
          ],
        },
      ],
    },
  },
};


export { I18N, LEGAL_DOCUMENTS };
