import {
  BUSINESS_ADDRESS,
  BUSINESS_ADDRESS_EN,
  BUSINESS_NAME,
  BUSINESS_REG_NUMBER,
  ECOMMERCE_REG_NUMBER,
  LANDLINE_PHONE,
  LEGAL_DOC_VERSION,
  REPRESENTATIVE_NAME,
  SUPPORT_EMAIL,
} from "./config";

const I18N = {
  ko: {
    languageOptionKo: "한국어",
    languageOptionEn: "English",
    legalMenu: "정책 메뉴",
    loadingApp: "앱 초기화 중...",
    authIntro: "AI 음성 기록, 지금 시작하세요.",
    authSubcopy: "로그인 후 바로 파일 업로드와 변환을 시작할 수 있습니다.",
    authLanding: {
      badges: {
        free: "무료 월 10시간",
        pro: "Pro 월 8,800원(VAT 포함) 무제한",
        beta: "오픈 베타",
      },
      hero: "녹음만 올리세요. 바로 쓰는 구조화 녹취 문서가 나옵니다.",
      subcopy: "설교, 통화, 회의에 맞춰 AI가 듣고 교정하고 요약합니다. 결과는 TXT/DOCX와 기록본으로 바로 저장할 수 있습니다.",
      beforeLabel: "Before",
      beforeExample: "\"이번 주 광고 예산이 15% 초과됐고, 다음 주 수정안을 다시 공유해 주세요.\"",
      afterLabel: "After",
      afterTitle: "회의 기록 요약",
      afterBullets: [
        "안건: 예산 초과 15%",
        "결정: 수정안 재공유",
        "후속 조치: 일정/담당 재배정",
      ],
      pricingCta: "요금제 보기",
      oursCta: "OURS 소개 보기",
      featureCards: [
        {
          title: "전문 용어 정확도",
          body: "도메인 용어 사전 + 문맥 교정으로 오인식을 줄입니다.",
        },
        {
          title: "구조화된 문서 출력",
          body: "요약, 핵심 포인트, 후속 조치까지 바로 쓰는 형태로 제공합니다.",
        },
        {
          title: "2단계 엔진",
          body: "Whisper 전사 + Gemini 교정으로 속도와 품질을 함께 확보합니다.",
        },
      ],
      testimonialLabel: "베타 사용자 피드백",
      testimonials: [
        "\"회의록 정리 시간이 훨씬 단축됐어요.\"",
        "\"설교 요약본을 바로 저장할 수 있어 편합니다.\"",
        "\"전문 용어가 이전보다 덜 깨집니다.\"",
      ],
    },
    login: "로그인",
    signup: "회원가입",
    namePlaceholder: "이름",
    emailPlaceholder: "이메일",
    passwordPlaceholder: "비밀번호",
    processing: "처리 중...",
    orSocial: "또는 소셜 로그인",
    connecting: "연결 중...",
    continueGoogle: "Google로 계속하기",
    continueKakao: "Kakao로 계속하기",
    defaultUser: "로그인 사용자",
    sessionRemainingLabel: "세션 남은 시간",
    sessionChecking: "확인 중",
    sessionExpired: "만료됨",
    logout: "로그아웃",
    tabs: {
      transcribe: "변환",
      history: "히스토리",
      records: "기록본",
      settings: "설정",
    },
    legal: {
      openPrivacy: "개인정보처리방침",
      openTerms: "이용약관",
      openCompanyPolicy: "회사 정책",
      openNotice: "공지사항",
      openFaq: "자주 묻는 질문",
      docVersion: "문서 버전",
      close: "닫기",
    },
    transcriptionTypes: {
      sermon: "설교",
      phonecall: "통화",
      conversation: "회의",
    },
    contentStyles: {
      sermon: "설교",
      lecture: "강의",
      phonecall: "통화",
      meeting: "회의",
      forum: "포럼",
      debate: "토론",
    },
    recordCategories: {
      meeting_keywords: "회의 중요 키워드",
      clinical_notes: "진료 도움 기록",
      sermon_core_summary: "설교 핵심 요약",
    },
    transcribeSettings: "변환 설정",
    pickFile: "파일 선택",
    noFile: "선택된 파일 없음",
    transcribeStart: "변환 시작",
    transcribing: "변환 중...",
    transcribeResult: "변환 결과",
    taskId: "작업 ID",
    itemType: "유형",
    charCount: "문자 수",
    correctedText: "교정 텍스트",
    generateSummary: "설교 요약 생성",
    generateSummaryByType: {
      sermon: "설교 요약 생성",
      lecture: "강의 요약 생성",
      phonecall: "통화 기록 요약 생성",
      meeting: "회의 요약 생성",
      forum: "포럼 요약 생성",
      debate: "토론 요약 생성",
      conversation: "회의 요약 생성",
    },
    generatingSummary: "요약 생성 중...",
    summary: "요약",
    recordGenerateSave: "기록본 생성 및 저장",
    draft: "초안",
    drafting: "생성 중",
    save: "저장",
    saving: "저장 중",
    recordEditorPlaceholder: "{label} 내용을 여기에 편집하세요",
    historyTitle: "최근 변환 기록",
    recordsTitle: "저장 기록본",
    refresh: "새로고침",
    loading: "로딩...",
    noHistory: "변환 기록이 없습니다.",
    noRecords: "저장된 기록본이 없습니다.",
    load: "불러오기",
    selectedTypeHints: {
      sermon: "설교 흐름(본론/결론/기도) 중심으로 구조화합니다.",
      phonecall: "통화 화자 분리와 핵심 문장 중심으로 정리합니다.",
      conversation: "회의 안건/결정/후속 조치를 분리해 정리합니다.",
    },
    settingsTitle: "설정",
    settingsSubtitle: "정책 확인과 앱 환경을 관리합니다.",
    settingsLegalTitle: "법률 문서",
    settingsLegalHint: "개인정보처리방침, 이용약관, 회사 정책을 앱 내 문서 페이지에서 확인하세요.",
    settingsAppearanceTitle: "언어 및 테마",
    settingsAppearanceHint: "언어와 테마를 즉시 변경할 수 있습니다.",
    settingsLanguageLabel: "언어 선택",
    settingsThemeLabel: "테마 선택",
    settingsSupportTitle: "공지 및 도움말",
    settingsSupportHint: "업데이트 공지와 자주 묻는 질문을 앱 내 문서로 확인하세요.",
    settingsUsageTitle: "사용량 및 구독",
    settingsUsageHint: "이번 달 남은 사용 시간을 확인하고 구독 업그레이드를 진행할 수 있습니다.",
    usagePlanLabel: "현재 플랜",
    usageStatusLabel: "구독 상태",
    usageBillingProvider: "결제 공급자",
    usageCheckoutMode: "결제 모드",
    usageThisMonth: "이번 달 사용량",
    usageRemaining: "남은 시간",
    usageUnlimited: "무제한",
    usageLoading: "사용량 정보를 불러오는 중...",
    usageUnavailable: "사용량 정보를 아직 불러오지 못했습니다.",
    usageRefresh: "사용량 새로고침",
    usageUpgrade: "구독 업그레이드",
    usageManageSubscription: "구독 관리",
    usageCancelSubscription: "구독 취소",
    usageRequestRefund: "환불 요청",
    usageOpenPricing: "요금제 안내 보기",
    billingUnsupported: "현재 결제 설정에서는 앱 내 결제 호출이 비활성화되어 있습니다.",
    planLabels: {
      free: "Free",
      pro: "Pro",
      enterprise: "Enterprise",
      admin: "Admin",
    },
    billingStatusLabels: {
      inactive: "미구독",
      active: "활성",
      trialing: "체험중",
      checkout_pending: "결제 대기",
      checkout_canceled: "결제 취소",
      canceled: "해지",
      refund_requested: "환불 요청",
      refunded: "환불 완료",
      past_due: "미납",
      unpaid: "미납",
      incomplete: "미완료",
      incomplete_expired: "만료",
      unknown: "확인 필요",
    },
    clipboardCopy: "클립보드 복사",
    exportTxt: "TXT 저장/공유",
    exportDocx: "DOCX 저장/공유",
    privacy: {
      title: "개인정보처리방침 동의",
      version: `정책 버전: ${LEGAL_DOC_VERSION}`,
      body: "mallog24 이용 전 개인정보 처리 내용을 확인해주세요. 동의 후 로그인 및 음성 변환 기능을 사용할 수 있습니다.",
      summaryFile: "• 원본 음성 파일: 변환 처리 후 임시 저장소에서 지체 없이 삭제",
      summaryText: "• 변환 텍스트/기록본: 히스토리 및 기록 기능 제공 목적 범위 내 보관",
      summaryVendors: "• 처리 위탁: Supabase, OpenAI, Google(Gemini)",
      summarySocial: "• 소셜 로그인: Google/Kakao 계정 정보(이메일, 프로필, UID)",
      viewPolicy: "개인정보처리방침 전문 보기",
      viewTerms: "이용약관 보기",
      viewCompanyPolicy: "회사 정책 보기",
      check: "개인정보처리방침을 확인했고 동의합니다.",
      accept: "동의하고 시작하기",
      saving: "저장 중...",
    },
    notices: {
      socialLoginDone: "소셜 로그인이 완료되었습니다.",
      authDoneSignup: "회원가입/로그인이 완료되었습니다.",
      authDoneLogin: "로그인되었습니다.",
      signupDone: "회원가입이 완료되었습니다. 이메일 인증 후 로그인해주세요.",
      loggedOut: "로그아웃되었습니다.",
      fileSelected: "파일이 선택되었습니다.",
      transcribeDone: "변환이 완료되었습니다.",
      requestAccepted: "요청이 접수되었습니다.",
      historyLoaded: "히스토리 결과를 불러왔습니다.",
      summaryDone: "요약을 생성했습니다.",
      draftDone: "{label} 초안을 생성했습니다.",
      recordSaved: "기록본을 저장했습니다.",
      privacyAccepted: "개인정보처리방침 동의가 완료되었습니다.",
      copiedToClipboard: "{label} 내용을 클립보드에 복사했습니다.",
      openedShareTxt: "TXT 저장/공유 창을 열었습니다.",
      openedShareDocx: "DOCX 저장/공유 창을 열었습니다.",
      usageLoaded: "사용량 정보를 업데이트했습니다.",
      checkoutOpened: "결제 페이지를 열었습니다.",
      portalOpened: "구독 관리 페이지를 열었습니다.",
      subscriptionCancelDone: "구독 취소 요청이 접수되었습니다.",
      refundRequestDone: "환불 요청이 접수되었습니다.",
    },
    errors: {
      authRequired: "로그인 후 파일 변환을 사용할 수 있습니다.",
      authInputRequired: "이메일/비밀번호를 입력해주세요.",
      passwordMin: "비밀번호는 8자 이상이어야 합니다.",
      oauthUrlCreate: "OAuth URL 생성 실패",
      openLoginUrl: "로그인 URL을 열 수 없습니다.",
      socialStartFailed: "소셜 로그인 시작 실패",
      socialSessionFailed: "소셜 로그인 세션 처리 실패",
      socialFailedPrefix: "소셜 로그인 실패",
      fileTooLarge: "파일 크기는 100MB 이하여야 합니다.",
      filePickFailed: "파일 선택 실패",
      fileNotSelected: "먼저 파일을 선택해주세요.",
      transcribeFailed: "변환 요청 실패",
      taskNotFound: "작업 상태를 찾을 수 없습니다.",
      transcribeError: "변환 중 오류가 발생했습니다.",
      statusFailed: "상태 조회 실패",
      historyReadFailed: "히스토리 조회 실패",
      recordsReadFailed: "기록본 조회 실패",
      historyLoadFailed: "히스토리 불러오기 실패",
      historyLoadOnlyCompleted: "완료된 작업만 불러올 수 있습니다.",
      summaryFailed: "요약 실패",
      summaryNoText: "요약할 텍스트가 없습니다.",
      draftNeedLogin: "로그인 후 기록본 초안을 생성할 수 있습니다.",
      draftNoSource: "기록본 초안 생성에 필요한 변환 결과가 없습니다.",
      draftFailed: "기록본 초안 생성 실패",
      saveNeedLogin: "로그인 후 기록본 저장이 가능합니다.",
      saveNoContent: "저장할 기록본 내용이 없습니다.",
      saveFailed: "기록본 저장 실패",
      noExportContent: "내보낼 내용이 없습니다.",
      clipboardFailed: "클립보드 복사에 실패했습니다.",
      shareFailed: "공유 창을 열지 못했습니다.",
      exportModuleMissing: "파일 내보내기 모듈이 없습니다. 앱 의존성을 업데이트해 주세요.",
      shareUnavailable: "이 기기에서는 파일 공유를 지원하지 않습니다.",
      openPrivacyFailed: "개인정보처리방침 페이지를 열 수 없습니다.",
      openPrivacyLinkFailed: "개인정보처리방침 링크를 열 수 없습니다.",
      openTermsFailed: "이용약관 페이지를 열 수 없습니다.",
      openTermsLinkFailed: "이용약관 링크를 열 수 없습니다.",
      openCompanyPolicyFailed: "회사 정책 페이지를 열 수 없습니다.",
      openCompanyPolicyLinkFailed: "회사 정책 링크를 열 수 없습니다.",
      privacySaveFailed: "동의 상태 저장에 실패했습니다. 잠시 후 다시 시도해주세요.",
      usageReadFailed: "사용량 정보를 불러오지 못했습니다.",
      billingStatusReadFailed: "구독 상태를 불러오지 못했습니다.",
      billingCheckoutFailed: "결제 페이지를 열지 못했습니다.",
      billingPortalFailed: "구독 관리 페이지를 열지 못했습니다.",
      billingCancelFailed: "구독 취소 요청에 실패했습니다.",
      billingRefundFailed: "환불 요청에 실패했습니다.",
      openExternalFailed: "외부 페이지를 열 수 없습니다.",
      requestFailedPrefix: "요청 실패",
      timeout: "요청 시간이 초과되었습니다. 서버 상태를 확인해주세요.",
      transcribeLongRunning: "처리 시간이 길어지고 있습니다. 잠시 후 히스토리에서 다시 확인해주세요.",
    },
    taskState: {
      waiting: "변환 작업 대기 중...",
      queued: "변환 대기 중...",
      processing: "음성 인식/교정 처리 중...",
      done: "완료",
      uploading: "업로드 중...",
      historyLoading: "히스토리 불러오는 중...",
    },
    authErrors: {
      invalidCredentials: "이메일/비밀번호가 일치하지 않습니다. 기존 계정이 Google/Kakao로 가입된 계정이면 소셜 로그인 버튼을 사용하세요.",
      emailNotConfirmed: "이메일 인증이 완료되지 않았습니다. 인증 메일 확인 후 다시 로그인해주세요.",
      timeout: "인증 서버 응답이 지연되고 있습니다. 잠시 후 다시 시도해주세요.",
      default: "인증 처리 실패",
    },
  },
  en: {
    languageOptionKo: "Korean",
    languageOptionEn: "English",
    legalMenu: "Legal menu",
    loadingApp: "Initializing app...",
    authIntro: "Start AI speech records now.",
    authSubcopy: "Sign in to upload files and start transcription.",
    authLanding: {
      badges: {
        free: "Free 10h/mo",
        pro: "Pro KRW 8,800 (VAT included) unlimited",
        beta: "Open beta",
      },
      hero: "Upload your recording. Get a structured transcript you can use right away.",
      subcopy: "For sermons, calls, and meetings, AI listens, corrects, and summarizes. Save outputs instantly as TXT/DOCX and reusable records.",
      beforeLabel: "Before",
      beforeExample: "\"This week’s ad budget exceeded by 15%. Please share the revised plan again next week.\"",
      afterLabel: "After",
      afterTitle: "Meeting Record Summary",
      afterBullets: [
        "Agenda: Budget overspent by 15%",
        "Decision: Revised plan will be shared",
        "Next action: Reassign timeline/owner",
      ],
      pricingCta: "View pricing",
      oursCta: "About OURS",
      featureCards: [
        {
          title: "Accurate domain terms",
          body: "Domain dictionaries + context correction reduce misrecognitions.",
        },
        {
          title: "Structured output",
          body: "Get summaries, key points, and follow-up actions in a ready-to-use format.",
        },
        {
          title: "Two-stage engine",
          body: "Whisper transcription + Gemini correction balances speed and quality.",
        },
      ],
      testimonialLabel: "Beta user feedback",
      testimonials: [
        "\"Meeting-note cleanup time dropped significantly.\"",
        "\"It’s convenient to save sermon summaries right away.\"",
        "\"Domain terms break less than before.\"",
      ],
    },
    login: "Log In",
    signup: "Sign Up",
    namePlaceholder: "Name",
    emailPlaceholder: "Email",
    passwordPlaceholder: "Password",
    processing: "Processing...",
    orSocial: "or continue with social login",
    connecting: "Connecting...",
    continueGoogle: "Continue with Google",
    continueKakao: "Continue with Kakao",
    defaultUser: "Signed-in user",
    sessionRemainingLabel: "Session expires in",
    sessionChecking: "Checking...",
    sessionExpired: "Expired",
    logout: "Log out",
    tabs: {
      transcribe: "Transcribe",
      history: "History",
      records: "Records",
      settings: "Settings",
    },
    legal: {
      openPrivacy: "Privacy Policy",
      openTerms: "Terms of Service",
      openCompanyPolicy: "Company Policy",
      openNotice: "Notices",
      openFaq: "FAQ",
      docVersion: "Doc version",
      close: "Close",
    },
    transcriptionTypes: {
      sermon: "Sermon",
      phonecall: "Call",
      conversation: "Meeting",
    },
    contentStyles: {
      sermon: "Sermon",
      lecture: "Lecture",
      phonecall: "Call",
      meeting: "Meeting",
      forum: "Forum",
      debate: "Debate",
    },
    recordCategories: {
      meeting_keywords: "Meeting Keywords",
      clinical_notes: "Clinical Notes",
      sermon_core_summary: "Sermon Core Summary",
    },
    transcribeSettings: "Transcription Settings",
    pickFile: "Choose File",
    noFile: "No file selected",
    transcribeStart: "Start Transcription",
    transcribing: "Transcribing...",
    transcribeResult: "Transcription Result",
    taskId: "Task ID",
    itemType: "Type",
    charCount: "Characters",
    correctedText: "Corrected Text",
    generateSummary: "Generate Summary",
    generateSummaryByType: {
      sermon: "Generate Sermon Summary",
      lecture: "Generate Lecture Summary",
      phonecall: "Generate Call Summary",
      meeting: "Generate Meeting Summary",
      forum: "Generate Forum Summary",
      debate: "Generate Debate Summary",
      conversation: "Generate Meeting Summary",
    },
    generatingSummary: "Generating summary...",
    summary: "Summary",
    recordGenerateSave: "Generate & Save Records",
    draft: "Draft",
    drafting: "Drafting",
    save: "Save",
    saving: "Saving",
    recordEditorPlaceholder: "Edit {label} content here",
    historyTitle: "Recent History",
    recordsTitle: "Saved Records",
    refresh: "Refresh",
    loading: "Loading...",
    noHistory: "No transcription history.",
    noRecords: "No saved records.",
    load: "Load",
    selectedTypeHints: {
      sermon: "Structures content by sermon flow (message/application/prayer).",
      phonecall: "Focuses on speaker separation and core call statements.",
      conversation: "Separates agenda, decisions, and action items for meetings.",
    },
    settingsTitle: "Settings",
    settingsSubtitle: "Manage legal documents and app preferences.",
    settingsLegalTitle: "Legal Documents",
    settingsLegalHint: "Review privacy policy, terms of service, and company policy in the in-app document page.",
    settingsAppearanceTitle: "Language & Theme",
    settingsAppearanceHint: "Change language and theme instantly.",
    settingsLanguageLabel: "Language",
    settingsThemeLabel: "Theme",
    settingsSupportTitle: "Notices & Help",
    settingsSupportHint: "Read product updates and frequently asked questions in the in-app document page.",
    settingsUsageTitle: "Usage & Subscription",
    settingsUsageHint: "Check remaining monthly time and open subscription actions.",
    usagePlanLabel: "Current plan",
    usageStatusLabel: "Subscription status",
    usageBillingProvider: "Billing provider",
    usageCheckoutMode: "Checkout mode",
    usageThisMonth: "This month usage",
    usageRemaining: "Remaining",
    usageUnlimited: "Unlimited",
    usageLoading: "Loading usage information...",
    usageUnavailable: "Usage information is not available yet.",
    usageRefresh: "Refresh usage",
    usageUpgrade: "Upgrade subscription",
    usageManageSubscription: "Manage subscription",
    usageCancelSubscription: "Cancel subscription",
    usageRequestRefund: "Request refund",
    usageOpenPricing: "Open pricing page",
    billingUnsupported: "In-app checkout is currently disabled for this billing setup.",
    planLabels: {
      free: "Free",
      pro: "Pro",
      enterprise: "Enterprise",
      admin: "Admin",
    },
    billingStatusLabels: {
      inactive: "Inactive",
      active: "Active",
      trialing: "Trialing",
      checkout_pending: "Checkout pending",
      checkout_canceled: "Checkout canceled",
      canceled: "Canceled",
      refund_requested: "Refund requested",
      refunded: "Refunded",
      past_due: "Past due",
      unpaid: "Unpaid",
      incomplete: "Incomplete",
      incomplete_expired: "Expired",
      unknown: "Unknown",
    },
    clipboardCopy: "Copy to Clipboard",
    exportTxt: "Save/Share TXT",
    exportDocx: "Save/Share DOCX",
    privacy: {
      title: "Privacy Policy Consent",
      version: `Policy version: ${LEGAL_DOC_VERSION}`,
      body: "Please review our privacy handling details before using mallog24. You can use login and transcription after consent.",
      summaryFile: "• Source audio files: removed from temporary storage after processing",
      summaryText: "• Transcribed text/records: retained only for history and record features",
      summaryVendors: "• Processors: Supabase, OpenAI, Google (Gemini)",
      summarySocial: "• Social login: Google/Kakao account data (email, profile, UID)",
      viewPolicy: "View full privacy policy",
      viewTerms: "View terms of service",
      viewCompanyPolicy: "View company policy",
      check: "I have reviewed and agree to the Privacy Policy.",
      accept: "Agree and Continue",
      saving: "Saving...",
    },
    notices: {
      socialLoginDone: "Social login completed.",
      authDoneSignup: "Sign-up and login completed.",
      authDoneLogin: "Logged in successfully.",
      signupDone: "Sign-up completed. Please verify your email before login.",
      loggedOut: "You have been logged out.",
      fileSelected: "File selected.",
      transcribeDone: "Transcription completed.",
      requestAccepted: "Request accepted.",
      historyLoaded: "Loaded selected history result.",
      summaryDone: "Summary generated.",
      draftDone: "{label} draft generated.",
      recordSaved: "Record saved.",
      privacyAccepted: "Privacy consent saved.",
      copiedToClipboard: "{label} copied to clipboard.",
      openedShareTxt: "TXT save/share sheet opened.",
      openedShareDocx: "DOCX save/share sheet opened.",
      usageLoaded: "Usage information updated.",
      checkoutOpened: "Checkout page opened.",
      portalOpened: "Subscription portal opened.",
      subscriptionCancelDone: "Subscription cancellation request submitted.",
      refundRequestDone: "Refund request submitted.",
    },
    errors: {
      authRequired: "Please log in to use transcription.",
      authInputRequired: "Please enter email and password.",
      passwordMin: "Password must be at least 8 characters.",
      oauthUrlCreate: "Failed to create OAuth URL.",
      openLoginUrl: "Unable to open login URL.",
      socialStartFailed: "Failed to start social login",
      socialSessionFailed: "Failed to process social login session",
      socialFailedPrefix: "Social login failed",
      fileTooLarge: "File size must be 100MB or less.",
      filePickFailed: "Failed to select file",
      fileNotSelected: "Please select a file first.",
      transcribeFailed: "Failed to request transcription",
      taskNotFound: "Task status not found.",
      transcribeError: "An error occurred during transcription.",
      statusFailed: "Failed to check task status",
      historyReadFailed: "Failed to fetch history",
      recordsReadFailed: "Failed to fetch records",
      historyLoadFailed: "Failed to load history item",
      historyLoadOnlyCompleted: "Only completed tasks can be loaded.",
      summaryFailed: "Failed to generate summary",
      summaryNoText: "No text available to summarize.",
      draftNeedLogin: "Log in to generate record drafts.",
      draftNoSource: "No source text available for draft generation.",
      draftFailed: "Failed to generate record draft",
      saveNeedLogin: "Log in to save records.",
      saveNoContent: "No record content to save.",
      saveFailed: "Failed to save record",
      noExportContent: "No content to export.",
      clipboardFailed: "Failed to copy to clipboard.",
      shareFailed: "Unable to open share sheet.",
      exportModuleMissing: "File export modules are missing. Please update app dependencies.",
      shareUnavailable: "File sharing is not available on this device.",
      openPrivacyFailed: "Unable to open the privacy policy page.",
      openPrivacyLinkFailed: "Unable to open privacy policy link.",
      openTermsFailed: "Unable to open terms of service page.",
      openTermsLinkFailed: "Unable to open terms of service link.",
      openCompanyPolicyFailed: "Unable to open company policy page.",
      openCompanyPolicyLinkFailed: "Unable to open company policy link.",
      privacySaveFailed: "Failed to save consent state. Please try again.",
      usageReadFailed: "Failed to load usage information.",
      billingStatusReadFailed: "Failed to load subscription status.",
      billingCheckoutFailed: "Failed to open checkout page.",
      billingPortalFailed: "Failed to open subscription portal.",
      billingCancelFailed: "Failed to cancel subscription.",
      billingRefundFailed: "Failed to request refund.",
      openExternalFailed: "Unable to open external page.",
      requestFailedPrefix: "Request failed",
      timeout: "Request timed out. Please check server status.",
      transcribeLongRunning: "This task is taking longer than expected. Please check it again from History shortly.",
    },
    taskState: {
      waiting: "Waiting for transcription task...",
      queued: "Queued...",
      processing: "Running speech recognition/correction...",
      done: "Done",
      uploading: "Uploading...",
      historyLoading: "Loading history item...",
    },
    authErrors: {
      invalidCredentials: "Email/password is incorrect. If this account was created with Google/Kakao, use social login.",
      emailNotConfirmed: "Email verification is not complete. Please verify your email first.",
      timeout: "Auth server response is delayed. Please try again shortly.",
      default: "Authentication failed",
    },
  },
};

const SUPPORT_CONTACT_KO = `문의: ${SUPPORT_EMAIL}`;
const SUPPORT_CONTACT_EN = `Contact: ${SUPPORT_EMAIL}`;
const SERVICE_INQUIRY_CONTACT_KO = `서비스 관련 문의: ${SUPPORT_EMAIL}`;
const SERVICE_INQUIRY_CONTACT_EN = `Service inquiries: ${SUPPORT_EMAIL}`;
const BUSINESS_DISCLOSURE_KO = [
  `상호: ${BUSINESS_NAME}`,
  `사업자등록번호: ${BUSINESS_REG_NUMBER}`,
  `유선전화번호: ${LANDLINE_PHONE}`,
  `사업장주소: ${BUSINESS_ADDRESS}`,
  `대표: ${REPRESENTATIVE_NAME}`,
  `통신판매신고번호: ${ECOMMERCE_REG_NUMBER}`,
];
const BUSINESS_DISCLOSURE_EN = [
  `Company name: ${BUSINESS_NAME}`,
  `Business registration no.: ${BUSINESS_REG_NUMBER}`,
  `Landline: ${LANDLINE_PHONE}`,
  `Business address: ${BUSINESS_ADDRESS_EN}`,
  `Representative (CEO): ${REPRESENTATIVE_NAME}`,
  `E-commerce registration no.: ${ECOMMERCE_REG_NUMBER}`,
];

const LEGAL_DOCUMENTS = {
  ko: {
    privacy: {
      title: "개인정보처리방침",
      version: LEGAL_DOC_VERSION,
      updatedAt: "최종 업데이트: 2026년 2월 21일",
      sections: [
        {
          title: "1. 처리 항목",
          body: [
            "회원정보(이메일/UID), 소셜로그인 정보, 업로드 음성, 변환 텍스트, 기록본, 접속/오류 로그를 처리할 수 있습니다.",
          ],
        },
        {
          title: "2. 처리 목적",
          body: [
            "로그인/계정보호, 전사·교정·요약·기록본 기능 제공, 서비스 보안 및 고객지원 목적입니다.",
          ],
        },
        {
          title: "3. 보관 및 파기",
          body: [
            "원본 음성은 임시 저장 후 처리 완료 시 지체 없이 삭제합니다.",
            "변환 결과/기록본은 기능 제공 범위 내 보관되며 삭제 요청 또는 계정 종료 시 파기됩니다.",
          ],
        },
        {
          title: "4. 위탁 및 국외 처리",
          body: [
            "Supabase(인증/DB), OpenAI(Whisper), Google(Gemini)를 이용하며 API 처리 과정에서 국외 서버 처리가 발생할 수 있습니다.",
          ],
        },
        {
          title: "5. 이용자 권리",
          body: [
            "열람·정정·삭제·처리정지를 요청할 수 있으며, 문의 메일로 접수 시 합리적 기간 내 안내합니다.",
            "민감정보 업로드는 지양해 주세요.",
          ],
        },
        {
          title: "6. 문의",
          body: [SUPPORT_CONTACT_KO],
        },
      ],
    },
    terms: {
      title: "이용약관",
      version: LEGAL_DOC_VERSION,
      updatedAt: "시행일: 2026년 2월 23일",
      sections: [
        {
          title: "1. 서비스 범위",
          body: [
            "mallog24는 음성 전사/교정/요약/기록본 저장 기능을 제공합니다.",
            "외부 API 연동 특성상 처리시간과 결과 품질은 환경에 따라 달라질 수 있습니다.",
          ],
        },
        {
          title: "2. 요금제 및 상품 정보",
          body: [
            "계정·세션 관리 책임은 이용자에게 있으며, 무료 플랜은 월간 사용량 한도가 적용됩니다.",
            "유료 상품은 상품명, 월 이용요금, 이용기간, 제공기능을 서비스 화면에 명시합니다.",
            "현재 기준 유료 상품은 mallog24 Pro 월간 구독(월 8,800원, VAT 포함)이며 결제 승인 시점부터 1개월 단위 자동 갱신됩니다.",
          ],
        },
        {
          title: "3. 결제 및 구독 등록 절차",
          body: [
            "로그인 후 요금제 화면에서 상품 선택 → 결제대행사 체크아웃에서 상품명/금액/결제주기/약관 확인 → 결제 승인 순서로 진행됩니다.",
            "결제 승인 즉시 구독이 활성화되며, 다음 결제일부터 중단하려면 결제 주기 종료 전에 구독 관리에서 해지해야 합니다.",
          ],
        },
        {
          title: "4. 환불 규정",
          body: [
            "결제 후 7일 이내, 사용 이력이 없는 경우 전액 환불을 요청할 수 있습니다.",
            "사용 이력이 있는 경우 당월 부분 환불은 제한될 수 있으며, 해지는 다음 결제일부터 반영됩니다.",
            "중복 결제·시스템 오류 등 확인된 과오금은 전액 환불합니다.",
            "전자상거래법 등 관련 법령이 본 규정보다 우선하는 경우 해당 법령을 따릅니다.",
          ],
        },
        {
          title: "5. 사업자 및 결제 필수 고지",
          body: [
            ...BUSINESS_DISCLOSURE_KO,
            `고객지원 이메일: ${SUPPORT_EMAIL}`,
          ],
        },
        {
          title: "6. 이용자 책임",
          body: [
            "업로드 자료에 대한 적법한 권리를 보유해야 하며, 타인 권리 침해 자료 업로드를 금지합니다.",
          ],
        },
        {
          title: "7. 금지 행위",
          body: [
            "서비스 우회/공격/비정상 자동화 트래픽, 무단 재판매, 역설계 등 운영을 저해하는 행위를 금지합니다.",
          ],
        },
        {
          title: "8. 제한 및 면책",
          body: [
            "약관 위반 또는 보안위험 시 이용이 제한될 수 있습니다.",
            "전사 결과는 보조 도구이며 최종 검토 책임은 이용자에게 있습니다.",
          ],
        },
        {
          title: "9. 문의",
          body: [SUPPORT_CONTACT_KO],
        },
      ],
    },
    companyPolicy: {
      title: "회사 정책",
      version: LEGAL_DOC_VERSION,
      updatedAt: "최종 업데이트: 2026년 2월 23일",
      sections: [
        {
          title: "1. 운영 원칙",
          body: [
            "정확도·보안·안정성을 우선으로 제품을 개선합니다.",
            "사용자가 빠르게 기록을 재활용할 수 있는 단순한 흐름을 유지합니다.",
          ],
        },
        {
          title: "2. 데이터/보안 정책",
          body: [
            "최소 데이터 처리, 권한 분리, HTTPS, 토큰 검증, 요청 제한을 기본 통제로 적용합니다.",
          ],
        },
        {
          title: "3. 품질 정책",
          body: [
            "자동 생성 결과의 사용자 최종 검토를 권장하며, 도메인별 용어 사전/프롬프트를 지속 개선합니다.",
          ],
        },
        {
          title: "4. 책임 있는 AI",
          body: [
            "업로드 데이터는 서비스 목적 내에서만 처리합니다.",
            "불법/권리침해 신고는 내부 기준으로 검토 후 제한 조치할 수 있습니다.",
          ],
        },
        {
          title: "5. 유료상품 등록·변경 거버넌스",
          body: [
            "유료상품 신설/변경 시 상품명, 가격, 결제주기, 환불기준, 문의처를 표준 항목으로 확정합니다.",
            "결제대행사 콘솔 등록값과 서비스 화면(요금제/약관) 노출값을 교차 검증합니다.",
            "테스트 결제(승인/취소/실패/환불) 검증 완료 후 실결제를 활성화합니다.",
            "변경 시 문서 버전·적용일을 포함해 공지하고 주요 변경은 사전 안내합니다.",
          ],
        },
        {
          title: "6. 공지 및 지원",
          body: [
            "주요 정책/장애/기능 변경은 웹/앱 공지로 안내합니다.",
            SUPPORT_CONTACT_KO,
          ],
        },
        {
          title: "7. 사업자/결제 필수 고지",
          body: [
            ...BUSINESS_DISCLOSURE_KO,
            `고객지원 이메일: ${SUPPORT_EMAIL}`,
          ],
        },
      ],
    },
    notice: {
      title: "공지사항",
      version: LEGAL_DOC_VERSION,
      updatedAt: "최종 업데이트: 2026년 2월 21일",
      sections: [
        {
          title: "1. 서비스 안정화 안내",
          body: [
            "대용량 파일 처리 시 응답 지연이 발생할 수 있으며, 처리 상태는 작업 ID 기준으로 계속 확인할 수 있습니다.",
            "백엔드 점검이 필요한 경우 앱 내 배너와 웹 공지를 통해 사전 안내합니다.",
          ],
        },
        {
          title: "2. 정책 문서 개정 안내",
          body: [
            "개인정보처리방침/이용약관/회사정책 개정 시 문서 버전과 시행일을 함께 고지합니다.",
            "중요 변경 사항은 앱 초기 화면 또는 설정 탭에서 확인할 수 있습니다.",
          ],
        },
        {
          title: "3. 문의 채널",
          body: [
            SERVICE_INQUIRY_CONTACT_KO,
          ],
        },
      ],
    },
    faq: {
      title: "자주 묻는 질문 (FAQ)",
      version: LEGAL_DOC_VERSION,
      updatedAt: "최종 업데이트: 2026년 2월 21일",
      sections: [
        {
          title: "Q1. 로그인은 되는데 처리 시작이 느립니다.",
          body: [
            "네트워크 상태, 백엔드 인스턴스 워밍업, 외부 AI API 응답 시간에 따라 초기 지연이 발생할 수 있습니다.",
            "잠시 후 다시 시도하거나 앱을 재실행하면 개선되는 경우가 많습니다.",
          ],
        },
        {
          title: "Q2. 파일 업로드가 실패합니다.",
          body: [
            "파일 용량(최대 100MB), 포맷(mp3/wav/m4a/mp4/webm)과 로그인 상태를 먼저 확인해 주세요.",
            "오류가 반복되면 파일명을 단순화하고 네트워크를 변경해 다시 시도해 주세요.",
          ],
        },
        {
          title: "Q3. 전사 결과가 기대와 다릅니다.",
          body: [
            "배경소음이 적고 화자 구분이 명확한 원본 음성을 권장합니다.",
            "변환 후 요약/기록본 기능으로 문맥을 재정리하면 정확도를 높일 수 있습니다.",
          ],
        },
      ],
    },
  },
  en: {
    privacy: {
      title: "Privacy Policy",
      version: LEGAL_DOC_VERSION,
      updatedAt: "Last updated: February 21, 2026",
      sections: [
        {
          title: "1. Data We Process",
          body: [
            "We may process account data (email/UID), social-login data, uploaded audio, transcript text, saved records, and access/error logs.",
          ],
        },
        {
          title: "2. Purpose",
          body: [
            "Used for authentication, account security, transcription/correction/summarization, records, support, and service protection.",
          ],
        },
        {
          title: "3. Retention and Deletion",
          body: [
            "Source audio is kept in temporary storage and removed promptly after processing.",
            "Transcripts/records are kept for service features and removed on request or account closure.",
          ],
        },
        {
          title: "4. Processors and Overseas Processing",
          body: [
            "We use Supabase (auth/DB), OpenAI (Whisper), and Google (Gemini). API processing may involve overseas infrastructure.",
          ],
        },
        {
          title: "5. User Rights",
          body: [
            "You may request access, correction, deletion, and restriction via support email. Avoid uploading unnecessary sensitive data.",
          ],
        },
        {
          title: "6. Contact",
          body: [SUPPORT_CONTACT_EN],
        },
      ],
    },
    terms: {
      title: "Terms of Service",
      version: LEGAL_DOC_VERSION,
      updatedAt: "Effective date: February 23, 2026",
      sections: [
        {
          title: "1. Service Scope",
          body: [
            "mallog24 provides speech transcription, correction, summarization, and structured record features.",
            "Processing time and output quality may vary due to external API dependencies.",
          ],
        },
        {
          title: "2. Plans and Product Information",
          body: [
            "Users are responsible for account/session security. Free plans are subject to monthly usage quotas.",
            "Paid products disclose product name, monthly fee, service period, and included features in the UI.",
            "Current baseline paid product is mallog24 Pro Monthly Subscription (KRW 8,800/month, VAT included), auto-renewed every month after payment approval.",
          ],
        },
        {
          title: "3. Checkout and Subscription Registration Flow",
          body: [
            "Flow: login and plan selection -> payment-provider checkout review (product/amount/cycle/terms) -> payment approval.",
            "Subscription activates immediately after approval. To stop renewal, cancel before next billing date.",
          ],
        },
        {
          title: "4. Refund Policy",
          body: [
            "Full refund may be requested within 7 days after payment if no usage has occurred.",
            "If usage exists, partial refund for the current cycle may be limited; cancellation applies to the next cycle.",
            "Duplicate charges or confirmed billing errors are refunded in full.",
            "Mandatory consumer protection laws prevail where applicable.",
          ],
        },
        {
          title: "5. Business and Payment Mandatory Disclosure",
          body: [
            ...BUSINESS_DISCLOSURE_EN,
            `Support email: ${SUPPORT_EMAIL}`,
          ],
        },
        {
          title: "6. User Responsibility",
          body: [
            "Users must have lawful rights to uploaded content and must not infringe third-party rights.",
          ],
        },
        {
          title: "7. Prohibited Conduct",
          body: [
            "Abuse, attacks, bypass attempts, abnormal automation traffic, reverse engineering, and unauthorized resale are prohibited.",
          ],
        },
        {
          title: "8. Restriction and Disclaimer",
          body: [
            "Access may be limited for policy violations or security risks.",
            "Generated outputs are assistive; users are responsible for final review and use.",
          ],
        },
        {
          title: "9. Contact",
          body: [SUPPORT_CONTACT_EN],
        },
      ],
    },
    companyPolicy: {
      title: "Company Policy",
      version: LEGAL_DOC_VERSION,
      updatedAt: "Last updated: February 23, 2026",
      sections: [
        {
          title: "1. Operating Principles",
          body: [
            "We prioritize transcript quality, security, and reliability while keeping workflows simple and practical.",
          ],
        },
        {
          title: "2. Data and Security Standards",
          body: [
            "We apply data minimization, role separation, HTTPS, token validation, and request throttling as baseline controls.",
          ],
        },
        {
          title: "3. Quality Policy",
          body: [
            "Machine-generated outputs should be user-reviewed. Domain-specific prompts and dictionaries are continuously refined.",
          ],
        },
        {
          title: "4. Responsible AI Use",
          body: [
            "Uploaded data is used only for service functionality.",
            "Reported illegal or rights-infringing usage may lead to restrictions under internal policy.",
          ],
        },
        {
          title: "5. Paid Product Registration and Change Governance",
          body: [
            "Before launch/change, product name, price, billing cycle, refund rules, and support contact are finalized as mandatory fields.",
            "Payment-provider dashboard values are cross-checked against pricing and legal pages.",
            "Live checkout is enabled only after test transactions (success/cancel/failure/refund) and log verification pass.",
            "Material changes are announced with reason, effective date, and document version.",
          ],
        },
        {
          title: "6. Notice and Support",
          body: [
            "Major policy/feature/incident updates are announced via web or in-app notices.",
            SUPPORT_CONTACT_EN,
          ],
        },
        {
          title: "7. Business/Payment Mandatory Disclosure",
          body: [
            ...BUSINESS_DISCLOSURE_EN,
            `Support email: ${SUPPORT_EMAIL}`,
          ],
        },
      ],
    },
    notice: {
      title: "Notices",
      version: LEGAL_DOC_VERSION,
      updatedAt: "Last updated: February 21, 2026",
      sections: [
        {
          title: "1. Service Stability Notice",
          body: [
            "Large files may take longer to process. You can keep tracking status using the task ID.",
            "If backend maintenance is required, we provide advance notice in-app and on the web.",
          ],
        },
        {
          title: "2. Policy Revision Notice",
          body: [
            "When privacy/terms/company policy changes, we announce both document version and effective date.",
            "Major changes are highlighted on the app entry flow or in the Settings tab.",
          ],
        },
        {
          title: "3. Support Channel",
          body: [
            SERVICE_INQUIRY_CONTACT_EN,
          ],
        },
      ],
    },
    faq: {
      title: "Frequently Asked Questions (FAQ)",
      version: LEGAL_DOC_VERSION,
      updatedAt: "Last updated: February 21, 2026",
      sections: [
        {
          title: "Q1. Login works, but processing starts slowly.",
          body: [
            "Initial delays can happen due to network conditions, backend warm-up, or external AI API latency.",
            "Retrying after a short wait or relaunching the app often helps.",
          ],
        },
        {
          title: "Q2. Upload keeps failing.",
          body: [
            "Check file size (max 100MB), supported formats (mp3/wav/m4a/mp4/webm), and sign-in status.",
            "If it keeps failing, simplify the file name and retry on a different network.",
          ],
        },
        {
          title: "Q3. Transcript quality is lower than expected.",
          body: [
            "Use cleaner audio with clear speaker separation when possible.",
            "Post-process with summary/record features to improve final readability and structure.",
          ],
        },
      ],
    },
  },
};


export { I18N, LEGAL_DOCUMENTS };
