-- mallog24 billing refund request model
-- Run this in Supabase SQL Editor before using /api/billing/refund endpoint.

create table if not exists public.billing_refund_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  provider text not null default 'portone' check (provider in ('portone', 'tosspayments', 'stripe')),
  subscription_id text,
  payment_reference text,
  request_reason text,
  status text not null default 'requested'
    check (status in ('requested', 'manual_review', 'processing', 'refunded', 'rejected', 'failed')),
  decision_note text,
  refund_id text,
  metadata jsonb not null default '{}'::jsonb,
  processed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_billing_refund_requests_user_created
  on public.billing_refund_requests (user_id, created_at desc);

create index if not exists idx_billing_refund_requests_status
  on public.billing_refund_requests (status);

alter table if exists public.billing_refund_requests enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'billing_refund_requests'
      and policyname = 'billing_refund_requests_select_own'
  ) then
    create policy billing_refund_requests_select_own
      on public.billing_refund_requests
      for select
      to authenticated
      using (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'billing_refund_requests'
      and policyname = 'billing_refund_requests_insert_own'
  ) then
    create policy billing_refund_requests_insert_own
      on public.billing_refund_requests
      for insert
      to authenticated
      with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'billing_refund_requests'
      and policyname = 'billing_refund_requests_update_own'
  ) then
    create policy billing_refund_requests_update_own
      on public.billing_refund_requests
      for update
      to authenticated
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;
end $$;
