-- mallog24 saved records table
-- Run this in Supabase SQL Editor before using /api/records endpoints.

create table if not exists public.saved_records (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  category text not null check (category in ('meeting_keywords', 'clinical_notes', 'sermon_core_summary')),
  title text not null,
  content text not null,
  task_id text,
  source_type text,
  created_at timestamptz not null default now()
);

create index if not exists idx_saved_records_user_id_created_at
  on public.saved_records (user_id, created_at desc);

create index if not exists idx_saved_records_category
  on public.saved_records (category);

alter table if exists public.saved_records enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'saved_records'
      and policyname = 'saved_records_select_own'
  ) then
    create policy saved_records_select_own
      on public.saved_records
      for select
      to authenticated
      using (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'saved_records'
      and policyname = 'saved_records_insert_own'
  ) then
    create policy saved_records_insert_own
      on public.saved_records
      for insert
      to authenticated
      with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'saved_records'
      and policyname = 'saved_records_update_own'
  ) then
    create policy saved_records_update_own
      on public.saved_records
      for update
      to authenticated
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'saved_records'
      and policyname = 'saved_records_delete_own'
  ) then
    create policy saved_records_delete_own
      on public.saved_records
      for delete
      to authenticated
      using (auth.uid() = user_id);
  end if;
end $$;
