-- malloc24 saved records table
-- Run this in Supabase SQL Editor before using /api/records endpoints.

create table if not exists public.saved_records (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  category text not null check (category in ('meeting_keywords', 'clinical_notes', 'sermon_core_summary')),
  title text not null,
  content text not null,
  task_id text,
  source_type text,
  created_at timestamptz not null default now()
);

create index if not exists idx_saved_records_user_id_created_at
  on public.saved_records (user_id, created_at desc);

create index if not exists idx_saved_records_category
  on public.saved_records (category);
