-- mallog24 separated training data assets.
-- Run this in Supabase SQL Editor after transcription_jobs.sql, then run:
--   NOTIFY pgrst, 'reload schema';
--
-- This schema intentionally separates long-term training candidates from
-- operational transcription history. Use the private training-audio bucket
-- only after user consent and retention policy checks are in place.

insert into storage.buckets (id, name, public)
values ('training-audio', 'training-audio', false)
on conflict (id) do nothing;

create table if not exists public.training_audio_assets (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  task_id text,
  storage_bucket text not null default 'training-audio',
  storage_object_path text not null,
  source_storage_bucket text,
  source_storage_object_path text,
  source_mime_type text,
  original_filename text,
  audio_seconds integer not null default 0 check (audio_seconds >= 0),
  file_size_bytes bigint not null default 0 check (file_size_bytes >= 0),
  sha256 text,
  consent_status text not null default 'granted'
    check (consent_status in ('pending', 'granted', 'revoked')),
  retention_until timestamptz,
  deleted_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (storage_bucket, storage_object_path)
);

create table if not exists public.training_text_samples (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  task_id text,
  audio_asset_id bigint references public.training_audio_assets(id) on delete set null,
  source_type text not null default 'user_correction',
  category text,
  language text not null default 'ko',
  transcription_type text,
  raw_transcript text,
  current_result text,
  final_result text not null,
  quality_status text not null default 'candidate'
    check (quality_status in ('candidate', 'needs_review', 'approved', 'rejected')),
  train_split text not null default 'unassigned'
    check (train_split in ('unassigned', 'train', 'validation', 'test')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_training_audio_assets_user_created_at
  on public.training_audio_assets (user_id, created_at desc);

create index if not exists idx_training_audio_assets_task_id
  on public.training_audio_assets (task_id);

create index if not exists idx_training_audio_assets_consent_status
  on public.training_audio_assets (consent_status);

create index if not exists idx_training_audio_assets_source_path
  on public.training_audio_assets (source_storage_bucket, source_storage_object_path);

create index if not exists idx_training_text_samples_user_created_at
  on public.training_text_samples (user_id, created_at desc);

create index if not exists idx_training_text_samples_task_id
  on public.training_text_samples (task_id);

create index if not exists idx_training_text_samples_audio_asset_id
  on public.training_text_samples (audio_asset_id);

create index if not exists idx_training_text_samples_quality_split
  on public.training_text_samples (quality_status, train_split);

create or replace function public.set_training_data_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_training_audio_assets_updated_at on public.training_audio_assets;
create trigger set_training_audio_assets_updated_at
  before update on public.training_audio_assets
  for each row
  execute function public.set_training_data_updated_at();

drop trigger if exists set_training_text_samples_updated_at on public.training_text_samples;
create trigger set_training_text_samples_updated_at
  before update on public.training_text_samples
  for each row
  execute function public.set_training_data_updated_at();

alter table if exists public.training_audio_assets enable row level security;
alter table if exists public.training_text_samples enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'training_audio_assets'
      and policyname = 'training_audio_assets_select_own'
  ) then
    create policy training_audio_assets_select_own
      on public.training_audio_assets
      for select
      to authenticated
      using (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'training_audio_assets'
      and policyname = 'training_audio_assets_delete_own'
  ) then
    create policy training_audio_assets_delete_own
      on public.training_audio_assets
      for delete
      to authenticated
      using (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'training_text_samples'
      and policyname = 'training_text_samples_select_own'
  ) then
    create policy training_text_samples_select_own
      on public.training_text_samples
      for select
      to authenticated
      using (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'training_text_samples'
      and policyname = 'training_text_samples_delete_own'
  ) then
    create policy training_text_samples_delete_own
      on public.training_text_samples
      for delete
      to authenticated
      using (auth.uid() = user_id);
  end if;
end $$;
