-- Administrator-only per-transcription API usage metrics.
-- The backend must use the Supabase service_role key for inserts and reads.

create table if not exists public.transcription_usage_metrics (
  id bigint generated by default as identity primary key,
  task_id text not null unique,
  user_id uuid not null references auth.users(id) on delete cascade,
  usage_summary jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table if exists public.transcription_usage_metrics
  add column if not exists task_id text,
  add column if not exists user_id uuid,
  add column if not exists usage_summary jsonb default '{}'::jsonb,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

create unique index if not exists idx_transcription_usage_metrics_task_id
  on public.transcription_usage_metrics (task_id);

create index if not exists idx_transcription_usage_metrics_user_created_at
  on public.transcription_usage_metrics (user_id, created_at desc);

alter table if exists public.transcription_usage_metrics enable row level security;

-- No anon/authenticated policies are created. Even the owning user cannot read
-- provider usage or cost data directly; only the service-role backend can.
revoke all on table public.transcription_usage_metrics from public, anon, authenticated;
revoke all on sequence public.transcription_usage_metrics_id_seq from public, anon, authenticated;
grant all on table public.transcription_usage_metrics to service_role;
grant usage, select on sequence public.transcription_usage_metrics_id_seq to service_role;

notify pgrst, 'reload schema';
