-- mallog24 user correction samples table
-- Run this in Supabase SQL Editor before using /api/corrections.

create table if not exists public.user_correction_samples (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  task_id text,
  source_type text not null default 'record_draft',
  category text,
  language text not null default 'ko',
  original_text text not null,
  edited_text text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_user_correction_samples_user_id_created_at
  on public.user_correction_samples (user_id, created_at desc);

create index if not exists idx_user_correction_samples_task_id
  on public.user_correction_samples (task_id);

create index if not exists idx_user_correction_samples_category
  on public.user_correction_samples (category);

alter table if exists public.user_correction_samples enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'user_correction_samples'
      and policyname = 'user_correction_samples_select_own'
  ) then
    create policy user_correction_samples_select_own
      on public.user_correction_samples
      for select
      to authenticated
      using (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'user_correction_samples'
      and policyname = 'user_correction_samples_insert_own'
  ) then
    create policy user_correction_samples_insert_own
      on public.user_correction_samples
      for insert
      to authenticated
      with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'user_correction_samples'
      and policyname = 'user_correction_samples_delete_own'
  ) then
    create policy user_correction_samples_delete_own
      on public.user_correction_samples
      for delete
      to authenticated
      using (auth.uid() = user_id);
  end if;
end $$;
