-- mallog24 user glossary terms table
-- Run this in Supabase SQL Editor before using /api/glossary endpoints.

create table if not exists public.user_glossary_terms (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  term text not null,
  meaning text not null default '',
  aliases text[] not null default '{}',
  contexts text[] not null default '{}',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_glossary_terms_term_not_blank check (length(btrim(term)) > 0)
);

create index if not exists idx_user_glossary_terms_user_id_created_at
  on public.user_glossary_terms (user_id, created_at desc);

create index if not exists idx_user_glossary_terms_user_id_active
  on public.user_glossary_terms (user_id, is_active);

create unique index if not exists idx_user_glossary_terms_user_term_lower
  on public.user_glossary_terms (user_id, lower(term));

alter table if exists public.user_glossary_terms enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'user_glossary_terms'
      and policyname = 'user_glossary_terms_select_own'
  ) then
    create policy user_glossary_terms_select_own
      on public.user_glossary_terms
      for select
      to authenticated
      using (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'user_glossary_terms'
      and policyname = 'user_glossary_terms_insert_own'
  ) then
    create policy user_glossary_terms_insert_own
      on public.user_glossary_terms
      for insert
      to authenticated
      with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'user_glossary_terms'
      and policyname = 'user_glossary_terms_update_own'
  ) then
    create policy user_glossary_terms_update_own
      on public.user_glossary_terms
      for update
      to authenticated
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'user_glossary_terms'
      and policyname = 'user_glossary_terms_delete_own'
  ) then
    create policy user_glossary_terms_delete_own
      on public.user_glossary_terms
      for delete
      to authenticated
      using (auth.uid() = user_id);
  end if;
end $$;
